
import { VideoCase } from './types';

export const INITIAL_DATA: VideoCase[] = [
  // --- 1. Product Promo (Page 3) ---
  {
    id: '1-01',
    category: 'Promo',
    subcategory: 'Product Series',
    region: 'Global',
    robotType: 'BellaBot',
    clientName: 'BellaBot Promo',
    videoUrl: 'https://www.youtube.com/watch?v=A6vH-QyBTIw',
    rating: 5,
    keywords: ['Promo'],
  },
  {
    id: '1-02',
    category: 'Promo',
    subcategory: 'Product Series',
    region: 'Global',
    robotType: 'KettyBot',
    clientName: 'KettyBot Promo',
    videoUrl: 'https://www.youtube.com/watch?v=-5-eIQben-M',
    rating: 5,
    keywords: ['Promo'],
  },
  {
    id: '1-03',
    category: 'Promo',
    subcategory: 'Product Series',
    region: 'Global',
    robotType: 'SwiftBot',
    clientName: 'SwiftBot Promo',
    videoUrl: 'https://www.youtube.com/watch?v=taICF8-mlRI',
    rating: 5,
    keywords: ['Promo'],
  },
  {
    id: '1-04',
    category: 'Promo',
    subcategory: 'Product Series',
    region: 'Global',
    robotType: 'PuduBot 2',
    clientName: 'PuduBot 2 Promo',
    videoUrl: 'https://www.youtube.com/watch?v=45vUOogXXQc',
    rating: 5,
    keywords: ['Promo'],
  },
  {
    id: '1-05',
    category: 'Promo',
    subcategory: 'Product Series',
    region: 'Global',
    robotType: 'PuduBot',
    clientName: 'PuduBot Promo',
    videoUrl: 'https://www.youtube.com/watch?v=u2LVIVOK_cs',
    rating: 5,
    keywords: ['Promo'],
  },
  {
    id: '1-06',
    category: 'Promo',
    subcategory: 'Product Series',
    region: 'Global',
    robotType: 'CC1',
    clientName: 'CC1 Promo',
    videoUrl: 'https://www.youtube.com/watch?v=qoYgbgU5HNI',
    rating: 5,
    keywords: ['Promo'],
  },
  {
    id: '1-07',
    category: 'Promo',
    subcategory: 'Product Series',
    region: 'Global',
    robotType: 'HolaBot',
    clientName: 'HolaBot Promo',
    videoUrl: 'https://www.youtube.com/watch?v=NR0ZO0CE7WQ',
    rating: 5,
    keywords: ['Promo'],
  },
  {
    id: '1-08',
    category: 'Promo',
    subcategory: 'Product Series',
    region: 'Global',
    robotType: 'FlashBot',
    clientName: 'FlashBot Promo',
    videoUrl: 'https://www.youtube.com/watch?v=ZhNCUcAWEYU',
    rating: 5,
    keywords: ['Promo'],
  },
  {
    id: '1-09',
    category: 'Promo',
    subcategory: 'Product Series',
    region: 'Global',
    robotType: 'TigerBot',
    clientName: 'TigerBot Promo',
    videoUrl: 'https://www.youtube.com/watch?v=iNQbSRE7AS0',
    rating: 5,
    keywords: ['Promo'],
  },
  {
    id: '1-10',
    category: 'Promo',
    subcategory: 'Product Series',
    region: 'Global',
    robotType: 'Puductor 2',
    clientName: 'Puductor 2 Promo',
    videoUrl: 'https://www.youtube.com/watch?v=KCXWGo9-qvQ',
    rating: 5,
    keywords: ['Promo'],
  },
  {
    id: '1-11',
    category: 'Promo',
    subcategory: 'IOT Series',
    region: 'Global',
    robotType: 'IOT',
    clientName: 'Pager - Office',
    videoUrl: 'https://www.youtube.com/watch?v=9D0i8AK0kAM',
    rating: 5,
    keywords: ['Promo', 'Pager'],
  },
  {
    id: '1-12',
    category: 'Promo',
    subcategory: 'IOT Series',
    region: 'Global',
    robotType: 'IOT',
    clientName: 'Pager - Factory',
    videoUrl: 'https://www.youtube.com/watch?v=bgk9svAuMcs',
    rating: 5,
    keywords: ['Promo', 'Pager'],
  },
  {
    id: '1-13',
    category: 'Promo',
    subcategory: 'IOT Series',
    region: 'Global',
    robotType: 'IOT',
    clientName: 'Menu Locator',
    videoUrl: 'https://www.youtube.com/watch?v=6mus8nV2Mtc',
    rating: 5,
    keywords: ['Promo', 'Menu Locator'],
  },

  // --- 2. Catering: Western (Page 4-5) ---
  {
    id: '2-01',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Ireland',
    robotType: 'BellaBot',
    clientName: "Pandini's",
    videoUrl: 'https://www.youtube.com/watch?v=auZKiihVqOw',
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '2-02',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Ireland',
    robotType: 'HolaBot',
    clientName: "Pandini's",
    videoUrl: 'https://drive.google.com/file/d/1gecgUZV_UPxsAatYjrGFoTa3N-kMcIUn/view?usp=share_link', // Placeholder for "好啦-西餐-爱尔兰-20210621.mp4" if direct link not available, using Drive fallback or original filename text
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '2-03',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Australia',
    robotType: 'KettyBot',
    clientName: 'Maldron Hotel Newcastle',
    videoUrl: 'https://www.youtube.com/watch?v=ZSPDLhoukF8',
    rating: 2,
    keywords: ['Delivery Mode', 'Large Screen Ad'],
  },
  {
    id: '2-04',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Austria',
    robotType: 'BellaBot',
    clientName: 'Rose',
    videoUrl: 'https://drive.google.com/file/d/1gecgUZV_UPxsAatYjrGFoTa3N-kMcIUn/view?usp=share_link',
    rating: 1,
    keywords: ['Sticker'],
  },
  {
    id: '2-05',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Austria',
    robotType: 'BellaBot',
    clientName: 'Seerestaurant Rosé',
    videoUrl: 'https://youtu.be/-chH0aheS5A',
    rating: 3,
    keywords: ['Running', 'Sticker', 'Semi-outdoor'],
  },
  {
    id: '2-06',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Poland',
    robotType: 'BellaBot',
    clientName: 'PizzaHut',
    videoUrl: 'https://drive.google.com/file/d/1wJ5K61o9332BaqYQpASyZfIbEhFORlkD/view?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode', 'Sticker'],
  },
  {
    id: '2-07',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Poland',
    robotType: 'BellaBot',
    clientName: 'KFC',
    videoUrl: 'https://drive.google.com/file/d/1VrVwXyXUvPoYGCPut_Q-AsfW0pyRcgG6/view?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode', 'Sticker'],
  },
  {
    id: '2-08',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Poland',
    robotType: 'BellaBot',
    clientName: 'Sztuka Restaurant',
    videoUrl: 'https://www.youtube.com/watch?v=DGajUN1icAs',
    rating: 2,
    keywords: ['Delivery Mode', 'Sticker'],
  },
  {
    id: '2-09',
    category: 'Catering',
    subcategory: 'Western',
    region: 'UAE',
    robotType: 'BellaBot',
    clientName: 'Dolci&Capricci',
    videoUrl: 'https://drive.google.com/file/d/1hovdSQjqPkjwnAkUkWlbInXvkQb6-Cxe/view?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode', 'Sticker'],
  },
  {
    id: '2-10',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Netherlands',
    robotType: 'BellaBot',
    clientName: "Momma's Restaurant",
    videoUrl: 'https://www.youtube.com/watch?v=6cNWc8TJoI4',
    rating: 2,
    keywords: ['Sticker', 'Delivery Mode'],
  },
  {
    id: '2-11',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Canada',
    robotType: 'BellaBot',
    clientName: "Denny's",
    videoUrl: 'https://youtu.be/l1hQ5YTMJEw',
    rating: 3,
    keywords: ['Sticker', 'Delivery Mode', 'Touch'],
  },
  {
    id: '2-12',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Croatia',
    robotType: 'BellaBot',
    clientName: 'Marché Mövenpick',
    videoUrl: 'https://www.youtube.com/watch?v=1tYEvbZJ6Xk',
    rating: 3,
    keywords: ['Delivery Mode', 'Sticker', 'Birthday Mode'],
  },
  {
    id: '2-13',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Malta',
    robotType: 'BellaBot',
    clientName: 'MONDO',
    videoUrl: 'https://www.youtube.com/watch?v=XgS2z6lrcgY',
    rating: 2,
    keywords: ['Sticker', 'Touch', 'Delivery Mode'],
  },
  {
    id: '2-14',
    category: 'Catering',
    subcategory: 'Western',
    region: 'USA',
    robotType: 'BellaBot',
    clientName: 'Magic Noodle',
    videoUrl: 'https://www.youtube.com/watch?v=lK8WSf3jN2I',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '2-15',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Mexico',
    robotType: 'BellaBot',
    clientName: 'LAS ALITAS',
    videoUrl: 'https://www.youtube.com/watch?v=_lw8G35Netw',
    rating: 1,
    keywords: ['Running'],
  },
  {
    id: '2-16',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Europe',
    robotType: 'BellaBot',
    clientName: 'PizzaHut',
    videoUrl: 'https://drive.google.com/file/d/1mpoCTj5T1MVTDeFz0FKHAc54TazDjVDl/view?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode', 'Sticker'],
  },
  {
    id: '2-17',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Europe',
    robotType: 'BellaBot',
    clientName: 'KFC',
    videoUrl: 'https://drive.google.com/file/d/13sDjmvFxadAOoWHM8OJwDibOzskINoV8/view?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode', 'Sticker'],
  },
  {
    id: '2-18',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Japan',
    robotType: 'BellaBot',
    clientName: 'Restaurant',
    videoUrl: 'https://www.youtube.com/watch?v=X-4PAdpVz9g',
    rating: 3,
    keywords: ['Sticker', 'Delivery Mode', 'Touch', 'Birthday Mode'],
  },
  {
    id: '2-19',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Japan',
    robotType: 'KettyBot',
    clientName: "Coco's Restaurant",
    videoUrl: 'https://www.youtube.com/shorts/FuDpJOGmUVc',
    rating: 4,
    keywords: ['Delivery Mode', 'Tray', 'Button', 'Ad'],
  },
  {
    id: '2-20',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Saudi Arabia',
    robotType: 'BellaBot',
    clientName: 'South Grandstand (F1)',
    videoUrl: 'https://drive.google.com/file/d/1Iz_1m0hzLmjhRb8J4T4BdZf_sCh9ePJJ/view?usp=share_link',
    rating: 1,
    keywords: ['Sticker', 'Running'],
  },
  {
    id: '2-21',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Slovenia',
    robotType: 'BellaBot',
    clientName: "McDonald's",
    videoUrl: 'https://drive.google.com/drive/folders/1ZEUq_IWmJiWPk6wMuv0-0KIr2hGLeWXX?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode', 'Sticker'],
  },
  {
    id: '2-22',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Taiwan',
    robotType: 'BellaBot',
    clientName: 'Britishake',
    videoUrl: 'https://youtu.be/ny5LYHfwaWQ',
    rating: 3,
    keywords: ['Running', 'Sticker'],
  },
  {
    id: '2-23',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Spain',
    robotType: 'BellaBot',
    clientName: 'Comic Planet',
    videoUrl: 'https://www.youtube.com/watch?v=s4fwPwKqLVY',
    rating: 2,
    keywords: ['Sticker', 'Delivery Mode'],
  },
  {
    id: '2-24',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Spain',
    robotType: 'BellaBot',
    clientName: 'LA CHANCHA',
    videoUrl: 'https://www.youtube.com/watch?v=q4Q0e5c-t1E',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '2-25',
    category: 'Catering',
    subcategory: 'Western',
    region: 'New Zealand',
    robotType: 'BellaBot',
    clientName: "Andy's Burgers & Bar",
    videoUrl: 'https://drive.google.com/file/d/1tYLQjae0pLMeJZ0MJEapOx8zuJPp8SaY/view?usp=share_link',
    rating: 3,
    keywords: ['Sticker', 'Delivery Mode'],
  },
  {
    id: '2-26',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Italy',
    robotType: 'BellaBot',
    clientName: 'Kiyomi',
    videoUrl: 'https://drive.google.com/file/d/1BpDZgTVttlKAk6ZrdjjTs9Z0zmk6cYaw/view?usp=share_link',
    rating: 3,
    keywords: ['Delivery Mode', 'Birthday Mode', 'Dish Return', 'Touch'],
  },
  {
    id: '2-27',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Italy',
    robotType: 'BellaBot',
    clientName: 'Ristorante FuoriCittà Pizzeria',
    videoUrl: 'https://www.youtube.com/watch?v=Kc4z4MNYoX8',
    rating: 2,
    keywords: ['Delivery Mode', 'Sticker'],
  },
  {
    id: '2-28',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Italy',
    robotType: 'BellaBot',
    clientName: 'Casa',
    videoUrl: 'https://www.youtube.com/watch?v=YqpGTt_rY2Q',
    rating: 1,
    keywords: ['Running'],
  },

  // --- 2. Catering: Japanese/Korean (Page 5-6) ---
  {
    id: '2-JK-01',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'South Korea',
    robotType: 'PuduBot',
    clientName: 'Korean Restaurant',
    videoUrl: '', // Placeholder: "韩餐 Korean Restaurant"
    rating: 2,
    keywords: ['Delivery Mode', 'Running'],
  },
  {
    id: '2-JK-02',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'Canada',
    robotType: 'BellaBot',
    clientName: '168 Sushi',
    videoUrl: 'https://www.youtube.com/watch?v=AOGbJ_0znTg',
    rating: 2,
    keywords: ['Delivery Mode', 'Birthday Mode'],
  },
  {
    id: '2-JK-03',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'Malaysia',
    robotType: 'BellaBot',
    clientName: 'Sweetree',
    videoUrl: 'https://www.youtube.com/watch?v=L0aLoLQC6VI',
    rating: 2,
    keywords: ['Running'],
  },
  {
    id: '2-JK-04',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'Malaysia',
    robotType: 'KettyBot',
    clientName: 'Nippon Sushi',
    videoUrl: 'https://www.youtube.com/watch?v=SBZAxtXOpJI',
    rating: 2,
    keywords: ['Delivery Mode', 'Large Screen Ad'],
  },
  {
    id: '2-JK-05',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'Malaysia',
    robotType: 'KettyBot',
    clientName: 'Kawa Japanese Restaurant',
    videoUrl: 'https://www.youtube.com/watch?v=G4myzc0-SVo',
    rating: 2,
    keywords: ['Delivery Mode', 'Large Screen Ad'],
  },
  {
    id: '2-JK-06',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'USA',
    robotType: 'BellaBot',
    clientName: 'Sakura Japanese Resterant',
    videoUrl: 'https://drive.google.com/file/d/1MoM5yqt-6RMmaW0VAWMe6IcWyCF7TMFE/view?usp=share_link',
    rating: 2,
    keywords: ['Touch', 'Delivery Mode'],
  },
  {
    id: '2-JK-07',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'USA',
    robotType: 'BellaBot',
    clientName: 'Yama Sushi',
    videoUrl: 'https://www.youtube.com/watch?v=Z_bgBK4Ap20',
    rating: 1,
    keywords: ['Running'],
  },
  {
    id: '2-JK-08',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'USA',
    robotType: 'KettyBot',
    clientName: 'Hanu K BBQ',
    videoUrl: 'https://www.youtube.com/watch?v=EXPyNKSvs1s',
    rating: 1,
    keywords: ['Large Screen Ad', 'Running'],
  },
  {
    id: '2-JK-09',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'USA',
    robotType: 'KettyBot',
    clientName: 'FuGaKyu',
    videoUrl: 'https://www.youtube.com/shorts/Es4x0dDkk-Y',
    rating: 1,
    keywords: ['Running', 'Large Screen Ad'],
  },
  {
    id: '2-JK-10',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'Norway',
    robotType: 'KettyBot',
    clientName: 'Chimak House',
    videoUrl: 'https://www.youtube.com/watch?v=3V2i6BlxvHU',
    rating: 2,
    keywords: ['Delivery Mode', 'Large Screen Ad'],
  },
  {
    id: '2-JK-11',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'Japan',
    robotType: 'BellaBot',
    clientName: 'Soba Hamamipi',
    videoUrl: 'https://www.youtube.com/watch?v=P6SRXykBnIc',
    rating: 2,
    keywords: ['Delivery Mode', 'Touch'],
  },
  {
    id: '2-JK-12',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'Japan',
    robotType: 'BellaBot', // Also KettyBot listed
    clientName: 'Watami Yakiniku',
    videoUrl: 'https://www.youtube.com/watch?v=bGlRz6Z4CxE',
    rating: 2,
    keywords: ['Delivery Mode', 'Touch'],
  },
  {
    id: '2-JK-13',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'Japan',
    robotType: 'HolaBot',
    clientName: 'Kyushu Station Hotel Kokura',
    videoUrl: 'https://youtu.be/Y6783XWLkTY',
    rating: 3,
    keywords: ['Watch', 'Dish Return Mode'],
  },
  {
    id: '2-JK-14',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'Japan',
    robotType: 'KettyBot',
    clientName: 'Yakiniku Bugyo',
    videoUrl: 'https://www.youtube.com/watch?v=D3kH-77MGQM',
    rating: 3,
    keywords: ['Large Screen Ad', 'Tray', 'Running'],
  },
  {
    id: '2-JK-15',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'Taiwan',
    robotType: 'BellaBot', // & HolaBot
    clientName: 'Carbon',
    videoUrl: 'https://drive.google.com/file/d/1XIAPnYOcrSyo53b5GpzCOxwZz529lgeb/view?usp=share_link',
    rating: 2,
    keywords: ['Sticker'],
  },
  {
    id: '2-JK-16',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'Spain',
    robotType: 'BellaBot',
    clientName: 'Flower Wood',
    videoUrl: 'https://drive.google.com/file/d/1ut8Q-4PJIbu083FSIhplGHCUHgx44sjS/view?usp=share_link',
    rating: 2,
    keywords: ['Touch', 'Delivery Mode'],
  },
  {
    id: '2-JK-17',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'Spain',
    robotType: 'PuduBot',
    clientName: 'Sakura Restaurante',
    videoUrl: 'https://www.youtube.com/watch?v=14FMToh0rLM',
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '2-JK-18',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'UK',
    robotType: 'KettyBot',
    clientName: 'Gami Chicken',
    videoUrl: 'https://www.youtube.com/shorts/81dgWbi_BTU',
    rating: 1,
    keywords: ['Running'],
  },

  // --- 3. Catering: Fast Food (Page 7) ---
  {
    id: '3-01',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'Australia',
    robotType: 'PuduBot',
    clientName: "Dougie's Grill",
    videoUrl: '', // "欢乐送-汉堡店-澳大利亚-20210805.MP4"
    rating: 1,
    keywords: ['Delivery Mode', 'Running'],
  },
  {
    id: '3-02',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'Poland',
    robotType: 'KettyBot',
    clientName: 'Da Grasso',
    videoUrl: 'https://www.youtube.com/watch?v=t8gxwkESYlo',
    rating: 3,
    keywords: ['Delivery Mode', 'Large Screen Ad'],
  },
  {
    id: '3-03',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'Poland',
    robotType: 'KettyBot',
    clientName: 'Da Grasso Pizza',
    videoUrl: 'https://drive.google.com/drive/folders/1WBz6Ezn9UuXaCUIHjpmYQ3OdXF3Wrz3V?usp=share_link',
    rating: 1,
    keywords: ['Delivery Mode', 'Large Screen Ad', 'Sticker'],
  },
  {
    id: '3-04',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'Russia',
    robotType: 'PuduBot',
    clientName: 'Pizza Shop',
    videoUrl: '', // "俄罗斯-Pizza 店-20211019.mp4"
    rating: 2,
    keywords: ['Delivery Mode', 'Running'],
  },
  {
    id: '3-05',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'Russia',
    robotType: 'PuduBot',
    clientName: 'Pizza Factory',
    videoUrl: '', // "欢乐送-Pizza 店-俄罗斯-20211203.mp4"
    rating: 2,
    keywords: ['Delivery Mode', 'Running'],
  },
  {
    id: '3-06',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'Costa Rica',
    robotType: 'KettyBot',
    clientName: 'Burger King',
    videoUrl: 'https://drive.google.com/drive/folders/1IjglqzyP4JUD5kHtaOgXghOxQa4afOr7?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode', 'Large Screen Ad', 'Sticker'],
  },
  {
    id: '3-07',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'South Korea',
    robotType: 'PuduBot',
    clientName: 'Texas BBQ',
    videoUrl: '', // "欢乐送-汉堡店-韩国.MP4"
    rating: 2,
    keywords: ['Delivery Mode', 'Sticker'],
  },
  {
    id: '3-08',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'Canada',
    robotType: 'KettyBot',
    clientName: 'Burger King',
    videoUrl: 'https://drive.google.com/file/d/1fNdqNglig8ryPAiv_b1xnDSZsL_ksZL9/view?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode', 'Large Screen Ad'],
  },
  {
    id: '3-09',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'Canada',
    robotType: 'PuduBot 2',
    clientName: "Denny's",
    videoUrl: 'https://youtu.be/V9Q4rXYuAco',
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '3-10',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'Malaysia',
    robotType: 'PuduBot',
    clientName: 'Bistro',
    videoUrl: 'https://youtu.be/QJGGxbMhIHI',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '3-11',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'USA',
    robotType: 'KettyBot', // & Bella
    clientName: 'Avantis Ristorante',
    videoUrl: 'https://www.facebook.com/watch/?ref=search&v=398290171901873&external_log_id=2582a5ba',
    rating: 3,
    keywords: ['Host Mode', 'Large Screen Ad', 'Delivery Mode'],
  },
  {
    id: '3-12',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'USA',
    robotType: 'PuduBot',
    clientName: 'chicken-fil-a',
    videoUrl: 'https://youtu.be/t1sQoylLX9s',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '3-13',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'Saudi Arabia',
    robotType: 'PuduBot',
    clientName: 'Restaurant',
    videoUrl: 'https://youtube.com/shorts/tzUmSw8EpgA?feature=share',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '3-14',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'Guatemala',
    robotType: 'KettyBot',
    clientName: 'KFC',
    videoUrl: 'https://drive.google.com/drive/folders/1wN6XpirgL1gEut23TRXI9Mg3Pg5JKAhX?usp=share_link',
    rating: 3,
    keywords: ['Delivery Mode', 'Sticker', 'Large Screen Ad'],
  },
  {
    id: '3-15',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'New Zealand',
    robotType: 'BellaBot', // & HolaBot
    clientName: 'TVNZ',
    videoUrl: 'https://www.youtube.com/watch?v=_e41k94lrLc',
    rating: 2,
    keywords: ['Running'],
  },
  {
    id: '3-16',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'Chile',
    robotType: 'BellaBot',
    clientName: "McDonald's",
    videoUrl: 'https://drive.google.com/drive/folders/1UNHPHw5RkowdhzRGIELQ5-tRa2lpLjMB?usp=share_link',
    rating: 1,
    keywords: ['Delivery Mode'],
  },

  // --- 4. Catering: Hotpot (Page 7-8) ---
  {
    id: '4-01',
    category: 'Catering',
    subcategory: 'Hotpot',
    region: 'Malaysia',
    robotType: 'PuduBot 2',
    clientName: 'Akagui',
    videoUrl: 'https://youtube.com/shorts/qS0GzEYo6NE?feature=share',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '4-02',
    category: 'Catering',
    subcategory: 'Hotpot',
    region: 'USA',
    robotType: 'PuduBot',
    clientName: 'Haidilao',
    videoUrl: '', // "欢乐送-火锅店-美国.MP4"
    rating: 1,
    keywords: ['Birthday Mode'],
  },
  {
    id: '4-03',
    category: 'Catering',
    subcategory: 'Hotpot',
    region: 'Japan',
    robotType: 'BellaBot',
    clientName: 'SYABU-YO',
    videoUrl: 'https://youtu.be/4VIr-XfGZww',
    rating: 3,
    keywords: ['Running'],
  },
  {
    id: '4-04',
    category: 'Catering',
    subcategory: 'Hotpot',
    region: 'Thailand',
    robotType: 'BellaBot',
    clientName: 'You&I Premium Suki Buffet',
    videoUrl: 'https://www.youtube.com/watch?v=Xr0KS7TJOak',
    rating: 3,
    keywords: ['Running', 'Delivery Mode', 'Decoration'],
  },
  {
    id: '4-05',
    category: 'Catering',
    subcategory: 'Hotpot',
    region: 'Spain',
    robotType: 'BellaBot',
    clientName: 'Liuyishou',
    videoUrl: 'https://drive.google.com/file/d/1fJH7-fbaqk7bzVWATiH6lEkSnT11NFa3/view?usp=share_link',
    rating: 3,
    keywords: ['Delivery Mode', 'Sticker', 'Touch'],
  },
  {
    id: '4-06',
    category: 'Catering',
    subcategory: 'Hotpot',
    region: 'Spain',
    robotType: 'BellaBot',
    clientName: 'Mala Wuqing',
    videoUrl: 'https://drive.google.com/file/d/1vy4g6JHcebQIjjgCQiR3OHtRWBVuh77D/view?usp=share_link',
    rating: 2,
    keywords: ['Sticker', 'Delivery Mode'],
  },
  {
    id: '4-07',
    category: 'Catering',
    subcategory: 'Hotpot',
    region: 'Singapore',
    robotType: 'HolaBot',
    clientName: 'Black Knight Hotpot',
    videoUrl: 'https://youtube.com/shorts/xy7vUDMo8sg?feature=share',
    rating: 1,
    keywords: ['Dish Return'],
  },
  {
    id: '4-08',
    category: 'Catering',
    subcategory: 'Hotpot',
    region: 'China',
    robotType: 'BellaBot',
    clientName: 'Yemei Hotpot',
    videoUrl: 'https://www.youtube.com/watch?v=G8xwfyZPc6I',
    rating: 3,
    keywords: ['Sticker', 'Delivery Mode'],
  },
  {
    id: '4-09',
    category: 'Catering',
    subcategory: 'Hotpot',
    region: 'China',
    robotType: 'PuduBot',
    clientName: 'Haidilao',
    videoUrl: 'https://youtube.com/shorts/-JX71GmD2pA?feature=share',
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '4-10',
    category: 'Catering',
    subcategory: 'Hotpot',
    region: 'China',
    robotType: 'PuduBot',
    clientName: 'Haidilao',
    videoUrl: 'https://www.youtube.com/watch?v=x60mwsl_Kmk',
    rating: 3,
    keywords: ['Delivery Mode'],
  },

  // --- 5. Catering: Cafe (Page 8) ---
  {
    id: '5-01',
    category: 'Catering',
    subcategory: 'Cafe',
    region: 'Poland',
    robotType: 'BellaBot',
    clientName: 'Shell Café',
    videoUrl: 'https://drive.google.com/drive/folders/1-0woy1ziRmneOulgD6aWsW4ubdl7nB97?usp=share_link',
    rating: 1,
    keywords: ['Skin'],
  },
  {
    id: '5-02',
    category: 'Catering',
    subcategory: 'Cafe',
    region: 'Germany',
    robotType: 'BellaBot',
    clientName: 'Moness Coffee',
    videoUrl: 'https://www.youtube.com/watch?v=fW0e_E48iFA',
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '5-03',
    category: 'Catering',
    subcategory: 'Cafe',
    region: 'Tokyo',
    robotType: 'BellaBot',
    clientName: 'Starbucks',
    videoUrl: 'https://drive.google.com/file/d/1eqhz9PiMxl2xXCUj9-vojoOGdM4OHBBr/view?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode', 'Cover'],
  },
  {
    id: '5-04',
    category: 'Catering',
    subcategory: 'Cafe',
    region: 'Malaysia',
    robotType: 'PuduBot',
    clientName: 'TNL Bakery Cafe',
    videoUrl: 'https://fb.watch/jy4DxztMhc/',
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '5-05',
    category: 'Catering',
    subcategory: 'Cafe',
    region: 'Malaysia',
    robotType: 'PuduBot',
    clientName: 'Toast N Toast',
    videoUrl: 'https://youtu.be/dGifpvv6s8E',
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '5-06',
    category: 'Catering',
    subcategory: 'Cafe',
    region: 'Malaysia',
    robotType: 'PuduBot',
    clientName: 'Salam 1 Cafe',
    videoUrl: 'https://youtu.be/Ez8S4diZVWA',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '5-07',
    category: 'Catering',
    subcategory: 'Cafe',
    region: 'Malaysia',
    robotType: 'PuduBot',
    clientName: 'Tal Cafe',
    videoUrl: 'https://youtu.be/90dBLTwX-UQ',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '5-08',
    category: 'Catering',
    subcategory: 'Cafe',
    region: 'Malaysia',
    robotType: 'PuduBot',
    clientName: '42 Zest Cafe',
    videoUrl: 'https://youtu.be/4mTl-yi1l2g',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '5-09',
    category: 'Catering',
    subcategory: 'Cafe',
    region: 'USA',
    robotType: 'KettyBot',
    clientName: "Dunkin' Donuts",
    videoUrl: 'https://www.facebook.com/zpeedy.gonzales/videos/714301536506230/',
    rating: 2,
    keywords: ['Delivery Mode', 'Large Screen Ad'],
  },
  {
    id: '5-10',
    category: 'Catering',
    subcategory: 'Cafe',
    region: 'Switzerland',
    robotType: 'BellaBot',
    clientName: 'Coffee Island',
    videoUrl: 'https://drive.google.com/file/d/1wg6Lb0rO68x8oCXKrPqcpqBuiZaUjvO6/view?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode', 'Skin'],
  },
  {
    id: '5-11',
    category: 'Catering',
    subcategory: 'Cafe',
    region: 'India',
    robotType: 'BellaBot',
    clientName: 'Rasa Koffie',
    videoUrl: 'https://drive.google.com/file/d/1DAlJiVjekC_34DDOLaf98xRSEOHJzwSw/view?usp=share_link',
    rating: 1,
    keywords: ['Delivery Mode'],
  },

  // --- 6. Catering: Chinese (Page 9) ---
  {
    id: '6-01',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'Australia',
    robotType: 'KettyBot',
    clientName: 'Authentic Bites Dumpling House',
    videoUrl: 'https://www.youtube.com/watch?v=8fjDbUlOP4k',
    rating: 3,
    keywords: ['Delivery Mode', 'Scan Order'],
  },
  {
    id: '6-03',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'Australia',
    robotType: 'PuduBot',
    clientName: "MR Su's",
    videoUrl: '', // "欢乐送-中餐-澳大利亚-20210729.mp4"
    rating: 2,
    keywords: ['Sticker'],
  },
  {
    id: '6-04',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'Canada',
    robotType: 'BellaBot',
    clientName: 'Golden Ocean Seafood Restaurant',
    videoUrl: 'https://drive.google.com/file/d/1mG4GMI9QVTOVwAIpf3G7AuoKDB7-gZzW/view?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '6-05',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'Malaysia',
    robotType: 'KettyBot',
    clientName: 'Ding Tai Feng',
    videoUrl: 'https://www.youtube.com/watch?v=gtsZXq_SNtE',
    rating: 2,
    keywords: ['Large Screen Ad', 'Running'],
  },
  {
    id: '6-06',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'Malaysia',
    robotType: 'KettyBot',
    clientName: 'YINZO KOPI',
    videoUrl: 'https://www.youtube.com/watch?v=seAX15R9Cx0',
    rating: 2,
    keywords: ['Delivery Mode', 'Large Screen Ad', 'Tray'],
  },
  {
    id: '6-07',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'USA',
    robotType: 'HolaBot',
    clientName: 'Sapporo',
    videoUrl: '', // "好啦-中餐-美国.MP4"
    rating: 1,
    keywords: ['Dish Return'],
  },
  {
    id: '6-08',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'USA',
    robotType: 'PuduBot',
    clientName: 'Dim Sum',
    videoUrl: '', // "欢乐送-粤式早茶店-美国.MP4"
    rating: 2,
    keywords: ['Birthday Mode', 'Sticker'],
  },
  {
    id: '6-09',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'Saudi Arabia',
    robotType: 'BellaBot',
    clientName: 'Yunnan SILK ROAD Restaurant',
    videoUrl: 'https://www.youtube.com/watch?v=uT0Lpsm9LJI',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '6-10',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'Taiwan',
    robotType: 'BellaBot',
    clientName: 'Tim Ho Wan',
    videoUrl: 'https://www.youtube.com/watch?v=HnzozEbvjFY',
    rating: 1,
    keywords: ['Running', 'Sticker'],
  },
  {
    id: '6-11',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'Taiwan',
    robotType: 'HolaBot',
    clientName: 'Din Tai Fung',
    videoUrl: '', // "好啦-鼎泰丰-台湾-20210902-01.mp4"
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '6-12',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'Hong Kong',
    robotType: 'KettyBot',
    clientName: 'BTW',
    videoUrl: 'https://www.youtube.com/watch?v=HaKVZ4CfAtg',
    rating: 4,
    keywords: ['Host Mode', 'Delivery Mode', 'Birthday Mode', 'Cover', 'Tray', 'Sticker'],
  },
  {
    id: '6-13',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'Hong Kong',
    robotType: 'KettyBot',
    clientName: "Oliver's Super Sandwiches",
    videoUrl: 'https://www.youtube.com/watch?v=iYanRKFk1DA',
    rating: 3,
    keywords: ['Delivery Mode', 'Cover', 'Large Screen Ad', 'Button'],
  },
  {
    id: '6-14',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'Singapore',
    robotType: 'BellaBot',
    clientName: 'Putien',
    videoUrl: 'https://www.youtube.com/shorts/LYx1FmnPwaU',
    rating: 1,
    keywords: ['Running'],
  },
  {
    id: '6-15',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'Singapore',
    robotType: 'PuduBot',
    clientName: 'Swee Choon Tim Sum',
    videoUrl: 'https://youtu.be/pSi5qgqOeno',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '6-16',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'Indonesia',
    robotType: 'BellaBot',
    clientName: 'Imperial Kitchen & Dimsum',
    videoUrl: 'https://www.youtube.com/watch?v=L34-b4ws-iE',
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '6-17',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'UK',
    robotType: 'BellaBot',
    clientName: 'TCB Restaurant',
    videoUrl: 'https://www.youtube.com/watch?v=VarpXXEZHbk',
    rating: 2,
    keywords: ['Delivery Mode', 'Running'],
  },

  // --- 7. Catering: Southeast Asian (Page 9-10) ---
  {
    id: '7-01',
    category: 'Catering',
    subcategory: 'Southeast Asian',
    region: 'Australia',
    robotType: 'PuduBot',
    clientName: 'Indian Restaurant',
    videoUrl: '', // "欢乐送-印度餐厅-澳大利亚-20211221.MP4"
    rating: 2,
    keywords: ['Delivery Mode', 'Multi-table'],
  },
  {
    id: '7-02',
    category: 'Catering',
    subcategory: 'Southeast Asian',
    region: 'Canada',
    robotType: 'KettyBot',
    clientName: 'Mekong Asian Cuisine',
    videoUrl: 'https://www.youtube.com/watch?v=je8qPq1vBx4',
    rating: 4,
    keywords: ['Delivery Mode', 'Large Screen Ad', 'Birthday Mode'],
  },
  {
    id: '7-03',
    category: 'Catering',
    subcategory: 'Southeast Asian',
    region: 'Malaysia',
    robotType: 'BellaBot',
    clientName: "Johnny's Restaurant",
    videoUrl: 'https://www.youtube.com/watch?v=cvij8TLwhdY',
    rating: 3,
    keywords: ['Sticker', 'Delivery Mode'],
  },
  {
    id: '7-04',
    category: 'Catering',
    subcategory: 'Southeast Asian',
    region: 'Malaysia',
    robotType: 'BellaBot',
    clientName: 'Gegey',
    videoUrl: 'https://drive.google.com/file/d/1G-6SMOHMLx9EY6r_lFNImIYQ4hVBg02A/view?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode', 'Sticker'],
  },
  {
    id: '7-05',
    category: 'Catering',
    subcategory: 'Southeast Asian',
    region: 'Malaysia',
    robotType: 'BellaBot',
    clientName: 'Black Canyon',
    videoUrl: 'https://youtu.be/f_LE_vvFqVU',
    rating: 3,
    keywords: ['Running', 'Sticker'],
  },
  {
    id: '7-06',
    category: 'Catering',
    subcategory: 'Southeast Asian',
    region: 'Malaysia',
    robotType: 'PuduBot',
    clientName: 'Beng Huat Asam Fish Chicken Rice',
    videoUrl: 'https://fb.watch/jy4lN9bntq/',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '7-07',
    category: 'Catering',
    subcategory: 'Southeast Asian',
    region: 'Malaysia',
    robotType: 'PuduBot',
    clientName: 'Ichiban Ramen',
    videoUrl: 'https://youtu.be/j-1-SlbtR_g',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '7-08',
    category: 'Catering',
    subcategory: 'Southeast Asian',
    region: 'Malaysia',
    robotType: 'PuduBot',
    clientName: 'Style Food Court Bukit Mertajam',
    videoUrl: 'https://youtu.be/cdrDi4_XaOk',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '7-09',
    category: 'Catering',
    subcategory: 'Southeast Asian',
    region: 'Malaysia',
    robotType: 'PuduBot',
    clientName: 'Lee Noodle',
    videoUrl: 'https://youtu.be/Irrf-yA9XCM',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '7-10',
    category: 'Catering',
    subcategory: 'Southeast Asian',
    region: 'Malaysia',
    robotType: 'PuduBot',
    clientName: 'Restoran Ahmad Khan',
    videoUrl: 'https://youtu.be/dY_ljNKLYC0',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '7-11',
    category: 'Catering',
    subcategory: 'Southeast Asian',
    region: 'Malaysia',
    robotType: 'PuduBot 2',
    clientName: 'Y&Y Restaurant',
    videoUrl: 'https://www.facebook.com/secure.robotics.malaysia/videos/539845578298742',
    rating: 3,
    keywords: ['Delivery Mode', 'Cover'],
  },
  {
    id: '7-12',
    category: 'Catering',
    subcategory: 'Southeast Asian',
    region: 'USA',
    robotType: 'KettyBot',
    clientName: 'Pholicious',
    videoUrl: 'https://www.youtube.com/watch?v=rl_4UtXMz8g',
    rating: 1,
    keywords: ['Running'],
  },
  {
    id: '7-13',
    category: 'Catering',
    subcategory: 'Southeast Asian',
    region: 'Hong Kong',
    robotType: 'PuduBot',
    clientName: 'Saravanna Bhavan',
    videoUrl: 'https://youtube.com/shorts/c0TLYiTx7jw?feature=share',
    rating: 1,
    keywords: ['Delivery Mode'],
  },

  // --- 8. Catering: Hotel/Dessert/Middle Eastern (Page 10-11) ---
  {
    id: '8-01',
    category: 'Catering',
    subcategory: 'Hotel Restaurant',
    region: 'Ireland',
    robotType: 'BellaBot',
    clientName: 'Nevins Newfield Inn',
    videoUrl: 'https://youtu.be/Tq4wb7KfSvA',
    rating: 3,
    keywords: ['Running'],
  },
  {
    id: '8-02',
    category: 'Catering',
    subcategory: 'Hotel Restaurant',
    region: 'Poland',
    robotType: 'BellaBot',
    clientName: 'Elements',
    videoUrl: 'https://www.youtube.com/watch?v=2mN5_BBFMMw',
    rating: 3,
    keywords: ['Delivery Mode', 'Host Mode'],
  },
  {
    id: '8-03',
    category: 'Catering',
    subcategory: 'Hotel Restaurant',
    region: 'Poland',
    robotType: 'BellaBot',
    clientName: 'Marriott Warsaw Hotel',
    videoUrl: 'https://drive.google.com/file/d/1kQwEcj6CJYDIo5JlUISoET_aQLhOQ1VP/view?usp=share_link',
    rating: 2,
    keywords: ['Sticker', 'Delivery Mode'],
  },
  {
    id: '8-04',
    category: 'Catering',
    subcategory: 'Hotel Restaurant',
    region: 'Poland',
    robotType: 'BellaBot', // & HolaBot
    clientName: 'Hotelu O3',
    videoUrl: 'https://www.youtube.com/watch?v=KZ644p7VAg8',
    rating: 4,
    keywords: ['Touch', 'IOT Automatic Door'],
  },
  {
    id: '8-05',
    category: 'Catering',
    subcategory: 'Hotel Restaurant',
    region: 'Poland',
    robotType: 'HolaBot',
    clientName: 'Cottonina Hotel',
    videoUrl: 'https://www.youtube.com/watch?v=DobG2n6lua4',
    rating: 2,
    keywords: ['Delivery Mode', 'Dish Return'],
  },
  {
    id: '8-06',
    category: 'Catering',
    subcategory: 'Hotel Restaurant',
    region: 'Japan',
    robotType: 'HolaBot',
    clientName: 'Torrent',
    videoUrl: 'https://youtu.be/K_g1fvA5UJo',
    rating: 3,
    keywords: ['Watch', 'Dish Return'],
  },
  {
    id: '8-07',
    category: 'Catering',
    subcategory: 'Hotel Restaurant',
    region: 'Hong Kong',
    robotType: 'BellaBot',
    clientName: 'Wetland Seasons Park',
    videoUrl: 'https://youtu.be/sDm8Xpe6IbE',
    rating: 2,
    keywords: ['Sticker', 'Running'],
  },
  {
    id: '8-08',
    category: 'Catering',
    subcategory: 'Hotel Restaurant',
    region: 'Hong Kong',
    robotType: 'FlashBot', // & HolaBot
    clientName: 'Alva Hotel',
    videoUrl: 'https://youtu.be/o2fBnMtlE7Y',
    rating: 3,
    keywords: ['Delivery Mode', 'Sticker', 'Combo'],
  },
  {
    id: '8-09',
    category: 'Catering',
    subcategory: 'Hotel Restaurant',
    region: 'Singapore',
    robotType: 'BellaBot',
    clientName: 'Shangri-La Hotel',
    videoUrl: 'https://www.youtube.com/watch?v=wMvX6ikyKeY',
    rating: 2,
    keywords: ['Sticker', 'Dish Return'],
  },
  {
    id: '8-10',
    category: 'Catering',
    subcategory: 'Dessert Shop',
    region: 'Germany',
    robotType: 'BellaBot', // & HolaBot
    clientName: 'Giovanni L.',
    videoUrl: 'https://www.youtube.com/watch?v=75AiJPhXVvM',
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '8-11',
    category: 'Catering',
    subcategory: 'Dessert Shop',
    region: 'Germany',
    robotType: 'HolaBot',
    clientName: 'Giovanni',
    videoUrl: 'https://youtu.be/jk3s-a5SQmU',
    rating: 2,
    keywords: ['Combo: Bella+Hola'],
  },
  {
    id: '8-12',
    category: 'Catering',
    subcategory: 'Middle Eastern',
    region: 'Dubai',
    robotType: 'BellaBot',
    clientName: 'Good food',
    videoUrl: 'https://www.youtube.com/watch?v=AMBf9fdXHkA',
    rating: 2,
    keywords: ['Sticker', 'Birthday Mode', 'Delivery Mode'],
  },
  {
    id: '8-13',
    category: 'Catering',
    subcategory: 'Middle Eastern',
    region: 'UAE',
    robotType: 'BellaBot',
    clientName: 'B-cafe',
    videoUrl: 'https://www.youtube.com/shorts/clPLt_tX4S8',
    rating: 2,
    keywords: ['Sticker', 'Running'],
  },
  {
    id: '8-14',
    category: 'Catering',
    subcategory: 'Middle Eastern',
    region: 'Netherlands',
    robotType: 'HolaBot',
    clientName: 'Landal Coldenhove',
    videoUrl: 'https://youtu.be/t2otX-pT6mQ',
    rating: 2,
    keywords: ['Combo: Bella+Hola'],
  },
  {
    id: '8-15',
    category: 'Catering',
    subcategory: 'Middle Eastern',
    region: 'Kuwait',
    robotType: 'BellaBot',
    clientName: 'Lebanese Restaurant',
    videoUrl: 'https://drive.google.com/file/d/1ABThT-soCn-sdhmUkSjJQoV6v7dQFEQo/view?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode', 'Host Mode'],
  },

  // --- 3. Retail: Supermarket (Page 11) ---
  {
    id: '3-01',
    category: 'Retail',
    subcategory: 'Supermarket',
    region: 'Andorra',
    robotType: 'BellaBot',
    clientName: 'Carrefour (Coca Cola)',
    videoUrl: 'https://drive.google.com/drive/folders/1Bzi0PIe9hwIAi4Au9F8ObUr5H5Dif3-v?usp=share_link',
    rating: 3,
    keywords: ['Sticker', 'Running', 'Tray Rack'],
  },
  {
    id: '3-02',
    category: 'Retail',
    subcategory: 'Supermarket',
    region: 'Chile',
    robotType: 'KettyBot',
    clientName: 'Walmart',
    videoUrl: 'https://drive.google.com/drive/folders/1ETjyJ9LqED58uEHgjGdVvZxsjKDt_pBS?usp=share_link',
    rating: 3,
    keywords: ['Sticker', 'Large Screen Ad'],
  },
  {
    id: '3-03',
    category: 'Retail',
    subcategory: 'Supermarket',
    region: 'Guyana',
    robotType: 'KettyBot',
    clientName: 'Guía en supermercado',
    videoUrl: 'https://drive.google.com/file/d/1jwXfXe8CXj_E71HR4Pd_K7BdbHqVcwLW/view?usp=share_link',
    rating: 3,
    keywords: ['Guide', 'Large Screen Ad', 'Cruise Mode'],
  },
  {
    id: '3-04',
    category: 'Retail',
    subcategory: 'Supermarket',
    region: 'Taiwan',
    robotType: 'BellaBot',
    clientName: 'Carrefour',
    videoUrl: 'https://drive.google.com/drive/folders/1iCO2Jj3KQL46x9f4KyTKO4dwfFD8Kgu7?usp=share_link',
    rating: 2,
    keywords: ['Sticker', 'Running'],
  },
  {
    id: '3-05',
    category: 'Retail',
    subcategory: 'Supermarket',
    region: 'Thailand',
    robotType: 'BellaBot',
    clientName: 'Gourmet Market',
    videoUrl: 'https://drive.google.com/file/d/1Au71WGEn3JC6P8QCAX84yJqPuINaYrhf/view?usp=share_link',
    rating: 2,
    keywords: ['Sticker', 'Running'],
  },
  {
    id: '3-06',
    category: 'Retail',
    subcategory: 'Supermarket',
    region: 'USA',
    robotType: 'KettyBot',
    clientName: 'Walmart',
    videoUrl: 'https://drive.google.com/drive/folders/1F7v1cZbIF7rPQwMJ2ML804pin5-gTM66?usp=share_link',
    rating: 2,
    keywords: ['Host Mode', 'Large Screen Ad', 'Sticker', 'Combo'],
  },
  {
    id: '3-07',
    category: 'Retail',
    subcategory: 'Supermarket',
    region: 'Japan',
    robotType: 'PuduBot',
    clientName: 'Supermarket',
    videoUrl: 'https://www.youtube.com/watch?v=4ELJ7139yDQ',
    rating: 2,
    keywords: ['Sticker', 'Cruise Mode'],
  },
  {
    id: '3-08',
    category: 'Retail',
    subcategory: 'Supermarket',
    region: 'Turkey',
    robotType: 'BellaBot',
    clientName: 'Carrefour',
    videoUrl: 'https://drive.google.com/drive/folders/17b0NptgIjM20Lk0qsLS5TNwGZmzdZy6-?usp=share_link',
    rating: 1,
    keywords: ['Running', 'Sticker'],
  },
  {
    id: '3-09',
    category: 'Retail',
    subcategory: 'Supermarket',
    region: 'Jordan',
    robotType: 'BellaBot',
    clientName: 'HEINZ',
    videoUrl: 'https://drive.google.com/file/d/1Nu3H-fPgQqyFXztguSW1i_9u9M_fAvJB/view?usp=share_link',
    rating: 1,
    keywords: ['Sticker', 'Running'],
  },
  {
    id: '3-10',
    category: 'Retail',
    subcategory: 'Supermarket',
    region: 'Saudi Arabia',
    robotType: 'KettyBot',
    clientName: 'Carrefour',
    videoUrl: 'https://www.youtube.com/shorts/7fuR0_AgZrA',
    rating: 1,
    keywords: ['Combo: Ketty+Bella'],
  },
  {
    id: '3-11',
    category: 'Retail',
    subcategory: 'Supermarket',
    region: 'Russia',
    robotType: 'KettyBot',
    clientName: 'Tabris',
    videoUrl: 'https://drive.google.com/file/d/1uWD3j2bHIAypQ_ZQJcfJWMHtmsuIKMss/view?usp=share_link',
    rating: 1,
    keywords: ['Large Screen Ad', 'Sticker', 'Combo: Ketty+Bella'],
  },
  {
    id: '3-12',
    category: 'Retail',
    subcategory: 'Supermarket',
    region: 'South Korea',
    robotType: 'PuduBot',
    clientName: 'Supermarket',
    videoUrl: '', // "欢乐送-超市-韩国-202003-01.MP4"
    rating: 2,
    keywords: ['Sticker', 'Cruise Mode'],
  },

  // --- 3. Retail: Shopping Mall (Page 12) ---
  {
    id: '3-13',
    category: 'Retail',
    subcategory: 'Shopping Mall',
    region: 'Saudi Arabia',
    robotType: 'KettyBot',
    clientName: 'Al Othaim Mall',
    videoUrl: 'https://www.youtube.com/watch?v=h6ZaGa8buC4',
    rating: 4,
    keywords: ['Host Mode', 'Large Screen Ad', 'Cruise Mode', 'Auto Recharge'],
  },
  {
    id: '3-14',
    category: 'Retail',
    subcategory: 'Shopping Mall',
    region: 'Malaysia',
    robotType: 'KettyBot',
    clientName: 'Sunway Velocity Mall',
    videoUrl: 'https://www.facebook.com/SunwayVelocityMall/videos/723174179226011',
    rating: 3,
    keywords: ['Host Mode', 'Large Screen Ad'],
  },
  {
    id: '3-15',
    category: 'Retail',
    subcategory: 'Shopping Mall',
    region: 'Europe',
    robotType: 'KettyBot',
    clientName: 'Mall',
    videoUrl: 'https://www.youtube.com/watch?v=ObeyK-xm2iw',
    rating: 3,
    keywords: ['Large Screen Ad', 'Cruise Mode'],
  },
  {
    id: '3-16',
    category: 'Retail',
    subcategory: 'Shopping Mall',
    region: 'Hong Kong',
    robotType: 'KettyBot',
    clientName: 'VELOCITY',
    videoUrl: 'https://www.facebook.com/wen.fun.9/videos/2893321200800194',
    rating: 3,
    keywords: ['Host Mode'],
  },
  {
    id: '3-17',
    category: 'Retail',
    subcategory: 'Shopping Mall',
    region: 'Philippines',
    robotType: 'KettyBot',
    clientName: 'AllDay Supermarket',
    videoUrl: 'https://www.facebook.com/PuduRobotics.pk/videos/1328758447971447',
    rating: 2,
    keywords: ['Large Screen Ad', 'Sticker'],
  },
  {
    id: '3-18',
    category: 'Retail',
    subcategory: 'Shopping Mall',
    region: 'China',
    robotType: 'PuduBot 2',
    clientName: 'Wanxiang',
    videoUrl: 'https://youtu.be/SN8wnfDJsGI',
    rating: 2,
    keywords: ['Delivery Mode', 'Running', 'Multi-robot scheduling'],
  },
  {
    id: '3-19',
    category: 'Retail',
    subcategory: 'Shopping Mall',
    region: 'Japan',
    robotType: 'PuduBot 2',
    clientName: 'Mall',
    videoUrl: 'https://twitter.com/_incubion/status/1639507527426805760/photo/1',
    rating: 1,
    keywords: ['Large Screen Ad'],
  },
  {
    id: '3-20',
    category: 'Retail',
    subcategory: 'Shopping Mall',
    region: 'Australia',
    robotType: 'KettyBot', // & Bella, PuduBot, Hola
    clientName: 'Al Othaim Mall',
    videoUrl: 'https://youtu.be/esBeWUHnz2g',
    rating: 2,
    keywords: ['Sticker'],
  },

  // --- 3. Retail: Others (Page 12-13) ---
  {
    id: '3-21',
    category: 'Retail',
    subcategory: 'Building Material',
    region: 'Netherlands',
    robotType: 'KettyBot',
    clientName: 'Praxis Noordwijk',
    videoUrl: 'https://www.youtube.com/watch?v=kevqdYZFdnw',
    rating: 4,
    keywords: ['Skin', 'Greeter', 'Large Screen Ad', 'Guide'],
  },
  {
    id: '3-22',
    category: 'Retail',
    subcategory: 'Electronics',
    region: 'Netherlands',
    robotType: 'KettyBot',
    clientName: 'MediaMarkt',
    videoUrl: 'https://www.youtube.com/watch?v=K34nPERi3Qk',
    rating: 4,
    keywords: ['Large Screen Ad', 'Cruise Mode', 'Guide', 'Skin', 'Greeter'],
  },
  {
    id: '3-23',
    category: 'Retail',
    subcategory: 'Electronics',
    region: 'Netherlands',
    robotType: 'BellaBot',
    clientName: 'Media Market',
    videoUrl: 'https://drive.google.com/file/d/1Zx_4M4ZDIXyBQzoRsQyEfJXQ1MPto3ET/view?usp=share_link',
    rating: 1,
    keywords: ['Skin'],
  },
  {
    id: '3-24',
    category: 'Retail',
    subcategory: 'Electronics',
    region: 'Austria',
    robotType: 'BellaBot', // & Hola
    clientName: 'Media Market',
    videoUrl: 'https://drive.google.com/file/d/1-EwvjI-K3fvSO1iOA_ga0gve1xQM_mTF/view?usp=share_link',
    rating: 1,
    keywords: ['Skin', 'Running'],
  },
  {
    id: '3-25',
    category: 'Retail',
    subcategory: 'Retail Brand',
    region: 'Jordan',
    robotType: 'BellaBot', // & Ketty
    clientName: 'Coca Cola',
    videoUrl: 'https://drive.google.com/file/d/1kmcd1FmElbcvbvl34cwQyuPOJFTkU1Cg/view?usp=share_link',
    rating: 1,
    keywords: ['Running', 'Touch'],
  },
  {
    id: '3-26',
    category: 'Retail',
    subcategory: 'Retail Brand',
    region: 'Jordan',
    robotType: 'BellaBot', // & Ketty
    clientName: 'M&M',
    videoUrl: 'https://drive.google.com/drive/folders/1tRb7_Bmmx5nqngCuz2EToagDfDc7E_wj?usp=share_link',
    rating: 1,
    keywords: ['Skin', 'Running'],
  },
  {
    id: '3-27',
    category: 'Retail',
    subcategory: 'Telecom',
    region: 'Australia', // OCR says Melbourne so Australia
    robotType: 'KettyBot',
    clientName: 'Tienda',
    videoUrl: 'https://drive.google.com/file/d/1oz2eKp6ZQNYlwPIsfmxQq8cvGM1-Jjmd/view?usp=share_link',
    rating: 1,
    keywords: ['Large Screen Ad', 'Running'],
  },

  // --- 4. Other: Medical (Page 13) ---
  {
    id: '4-01',
    category: 'Other',
    subcategory: 'Medical',
    region: 'Estonia',
    robotType: 'KettyBot',
    clientName: 'Tartu Ülikooli Kliinikumis',
    videoUrl: 'https://www.youtube.com/shorts/cpmRMVLMw-U',
    rating: 2,
    keywords: ['Greeter', 'Large Screen Ad', 'Auto Recharge'],
  },
  {
    id: '4-02',
    category: 'Other',
    subcategory: 'Medical',
    region: 'Hong Kong',
    robotType: 'PuduBot',
    clientName: 'HK Hospitals',
    videoUrl: 'https://youtu.be/eVrR6xqVQUg',
    rating: 3,
    keywords: ['Sticker', 'Dish Cover'],
  },
  {
    id: '4-03',
    category: 'Other',
    subcategory: 'Medical',
    region: 'Malaysia',
    robotType: 'BellaBot',
    clientName: 'Sunway Medical Center',
    videoUrl: 'https://drive.google.com/file/d/1moTB5MsbMbEU8HgM5RocPQGG8d7u1BEd/view?usp=share_link',
    rating: 3,
    keywords: ['Delivery Mode', 'Sticker', 'Birthday Mode'],
  },
  {
    id: '4-04',
    category: 'Other',
    subcategory: 'Medical',
    region: 'Japan',
    robotType: 'KettyBot',
    clientName: 'Karada Terrace',
    videoUrl: 'https://www.youtube.com/watch?v=5eio-T2mi0I',
    rating: 2,
    keywords: ['Delivery Mode', 'Large Screen Ad'],
  },
  {
    id: '4-05',
    category: 'Other',
    subcategory: 'Medical',
    region: 'Australia',
    robotType: 'KettyBot',
    clientName: 'mp orthodontics',
    videoUrl: 'https://drive.google.com/drive/folders/18dEBkLEDTmZyPRTKD3L_9jvOgiKzCiDY?usp=share_link',
    rating: 1,
    keywords: ['Large Screen Ad', 'Running'],
  },
  {
    id: '4-06',
    category: 'Other',
    subcategory: 'Medical',
    region: 'Japan',
    robotType: 'KettyBot',
    clientName: 'Hodogaya Eye Clinic',
    videoUrl: 'https://www.youtube.com/watch?v=iYQmjlvTkbg',
    rating: 2,
    keywords: ['Large Screen Ad', 'Delivery Mode', 'Host Mode'],
  },
  {
    id: '4-07',
    category: 'Other',
    subcategory: 'Medical',
    region: 'Thailand',
    robotType: 'BellaBot', // & Puductor
    clientName: 'Square Cabin Hospital',
    videoUrl: 'https://www.youtube.com/watch?v=EPkE4JWsTxs',
    rating: 2,
    keywords: ['Running'],
  },
  {
    id: '4-08',
    category: 'Other',
    subcategory: 'Medical',
    region: 'South Korea',
    robotType: 'PuduBot',
    clientName: 'Dental Clinic',
    videoUrl: '', // "欢乐送-牙科门诊-韩国-02.mov"
    rating: 3,
    keywords: ['Delivery Mode', 'Dish Cover'],
  },
  {
    id: '4-09',
    category: 'Other',
    subcategory: 'Medical',
    region: 'South Korea',
    robotType: 'PuduBot',
    clientName: 'Hospital',
    videoUrl: '', // "欢乐送-医院-韩国-01.MP4"
    rating: 1,
    keywords: ['Cruise Mode'],
  },
  {
    id: '4-10',
    category: 'Other',
    subcategory: 'Medical',
    region: 'Thailand',
    robotType: 'PuduBot',
    clientName: 'Hospital Ward',
    videoUrl: '', // "欢乐送-医院-泰国-20210823.mp4"
    rating: 1,
    keywords: ['Delivery Mode'],
  },

  // --- 4. Other: Office/Factory/Etc (Page 13-14) ---
  {
    id: '4-11',
    category: 'Other',
    subcategory: 'Office',
    region: 'Australia',
    robotType: 'PuduBot',
    clientName: 'Office',
    videoUrl: 'https://youtu.be/6hGBqvXEjwk',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '4-12',
    category: 'Other',
    subcategory: 'Office',
    region: 'Hong Kong',
    robotType: 'KettyBot',
    clientName: 'Innocore',
    videoUrl: 'https://drive.google.com/file/d/1n4B9s1XiqWoYrRFPYVzxy-HjZdgYWGgp/view?usp=share_link',
    rating: 2,
    keywords: ['Disinfection Spray'],
  },
  {
    id: '4-13',
    category: 'Other',
    subcategory: 'Office',
    region: 'Shenzhen',
    robotType: 'KettyBot', // & FlashBot
    clientName: 'Office',
    videoUrl: 'https://youtu.be/hPy6eNk5ToQ',
    rating: 4,
    keywords: ['Running', 'Host Mode', 'Cruise Mode', 'IOT'],
  },
  {
    id: '4-14',
    category: 'Other',
    subcategory: 'Event',
    region: 'UAE',
    robotType: 'BellaBot', // & Ketty
    clientName: 'FIRSTGULF',
    videoUrl: 'https://drive.google.com/file/d/1v65XbEZpw1mibfeu72R7EbCPQ9ZZAWy6/view?usp=share_link',
    rating: 1,
    keywords: ['Running'],
  },
  {
    id: '4-15',
    category: 'Other',
    subcategory: 'Event',
    region: 'UAE',
    robotType: 'KettyBot',
    clientName: 'FIRSTGULF',
    videoUrl: 'https://drive.google.com/file/d/1NbkH8ZWfm8xcHYLxm2JarvG6YNuqc1yo/view?usp=share_link',
    rating: 1,
    keywords: ['Combo: Ketty+Bella', 'Large Screen Ad'],
  },
  {
    id: '4-16',
    category: 'Other',
    subcategory: 'Studio',
    region: 'Italy',
    robotType: 'KettyBot',
    clientName: 'M8 Studio',
    videoUrl: 'https://www.youtube.com/watch?v=0lF12cvbSBo',
    rating: 3,
    keywords: ['Large Screen Ad', 'Host Mode'],
  },
  {
    id: '4-17',
    category: 'Other',
    subcategory: 'Event',
    region: 'Malaysia',
    robotType: 'PuduBot 2',
    clientName: 'Association Meeting',
    videoUrl: 'https://youtu.be/D2GVIcjtDBk',
    rating: 2,
    keywords: ['Delivery Mode', 'Multi-robot scheduling'],
  },
  {
    id: '4-18',
    category: 'Other',
    subcategory: 'Event',
    region: 'Saudi Arabia',
    robotType: 'BellaBot',
    clientName: 'MCIT',
    videoUrl: 'https://youtu.be/k6nZpfgIU4Y',
    rating: 2,
    keywords: ['Running'],
  },
  {
    id: '4-19',
    category: 'Other',
    subcategory: 'Event',
    region: 'Hong Kong',
    robotType: 'BellaBot',
    clientName: "Maxim's Online Supplier Forum",
    videoUrl: 'https://youtu.be/UXr2ijsdG1E',
    rating: 2,
    keywords: ['Running'],
  },
  {
    id: '4-20',
    category: 'Other',
    subcategory: 'Factory',
    region: 'China',
    robotType: 'PuduBot',
    clientName: 'Great Wall Development',
    videoUrl: 'https://youtu.be/cN4i7QDjoKg',
    rating: 3,
    keywords: ['Delivery Mode'],
  },
  {
    id: '4-21',
    category: 'Other',
    subcategory: 'Factory',
    region: 'Japan',
    robotType: 'HolaBot',
    clientName: 'Factory',
    videoUrl: 'https://youtu.be/mqTbo54wD14',
    rating: 3,
    keywords: ['Watch', 'Delivery Mode'],
  },
  {
    id: '4-22',
    category: 'Other',
    subcategory: 'Factory',
    region: 'Australia',
    robotType: 'PuduBot 2',
    clientName: 'Factory',
    videoUrl: 'https://youtube.com/shorts/rv0FvIEnJqo?feature=share',
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '4-23',
    category: 'Other',
    subcategory: 'Factory',
    region: 'Japan',
    robotType: 'HolaBot',
    clientName: 'Seiko Electric',
    videoUrl: 'https://youtu.be/fA-aNYg1sFM',
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '4-24',
    category: 'Other',
    subcategory: 'Automotive 4S',
    region: 'Netherlands',
    robotType: 'KettyBot',
    clientName: 'Nissan',
    videoUrl: 'https://www.youtube.com/watch?v=KyVCVUQGwdo',
    rating: 3,
    keywords: ['Host Mode', 'Large Screen Ad'],
  },
  {
    id: '4-25',
    category: 'Other',
    subcategory: 'Automotive 4S',
    region: 'Indonesia',
    robotType: 'BellaBot',
    clientName: 'Lexus',
    videoUrl: '', // "贝拉-4s 店-台湾-20210728.mp4"
    rating: 1,
    keywords: ['Running'],
  },
  {
    id: '4-26',
    category: 'Other',
    subcategory: 'Automotive 4S',
    region: 'Thailand',
    robotType: 'KettyBot',
    clientName: 'Honda',
    videoUrl: 'https://drive.google.com/drive/folders/1n4rrrmlH6Uy36NJiavZdjn7BpvTNJW-i?usp=share_link',
    rating: 1,
    keywords: ['Large Screen Ad', 'Running'],
  },
  {
    id: '4-27',
    category: 'Other',
    subcategory: 'Nursing Home',
    region: 'Japan',
    robotType: 'BellaBot',
    clientName: 'Smiling Park',
    videoUrl: 'https://drive.google.com/file/d/1AWNVujSOwVtwWih-Zxavl0G7mFliEmSH/view?usp=share_link',
    rating: 4,
    keywords: ['Delivery Mode', 'App Call'],
  },
  {
    id: '4-28',
    category: 'Other',
    subcategory: 'Nursing Home',
    region: 'South Korea',
    robotType: 'PuduBot',
    clientName: 'Nursing Home',
    videoUrl: '', // "欢乐送-养老院.mp4"
    rating: 3,
    keywords: ['Sticker', 'Dish Cover'],
  },

  // --- 5. Other: Transport/Entertainment (Page 15) ---
  {
    id: '5-01',
    category: 'Other',
    subcategory: 'Exhibition',
    region: 'Ethiopia',
    robotType: 'KettyBot',
    clientName: 'Ethio Telecom',
    videoUrl: 'https://www.youtube.com/watch?v=PeH_FC6EkP4',
    rating: 1,
    keywords: ['Large Screen Ad', 'Running'],
  },
  {
    id: '5-02',
    category: 'Other',
    subcategory: 'Transport',
    region: 'Russia',
    robotType: 'KettyBot',
    clientName: 'Train Station',
    videoUrl: 'https://drive.google.com/file/d/1tCPLQ-EDTX5Qj8iE4UbJS5sp57Q9mfy3/view?usp=share_link',
    rating: 2,
    keywords: ['Large Screen Ad', 'Host Mode'],
  },
  {
    id: '5-03',
    category: 'Other',
    subcategory: 'Transport',
    region: 'Russia',
    robotType: 'BellaBot',
    clientName: 'Sheremetyevo Airport',
    videoUrl: 'https://drive.google.com/file/d/1z34Uy2Ec2j5A__iNpTUq2iG6_T-EZI-W/view?usp=share_link',
    rating: 1,
    keywords: ['Running'],
  },
  {
    id: '5-04',
    category: 'Other',
    subcategory: 'Media',
    region: 'Europe',
    robotType: 'BellaBot',
    clientName: 'CGTN',
    videoUrl: 'https://drive.google.com/file/d/1U2UJWoNo18w9Rjl1B1otCyB2u7tOi6rF/view?usp=share_link',
    rating: 2,
    keywords: ['Touch', 'Delivery Mode'],
  },
  {
    id: '5-05',
    category: 'Other',
    subcategory: 'TV Show',
    region: 'Netherlands',
    robotType: 'BellaBot',
    clientName: 'WIE KENT NEDERLAND SHOW',
    videoUrl: 'https://youtu.be/bY6bEO363Vg',
    rating: 2,
    keywords: ['Running'],
  },
  {
    id: '5-06',
    category: 'Other',
    subcategory: 'Library',
    region: 'Canada',
    robotType: 'KettyBot',
    clientName: 'St.Catharines library',
    videoUrl: 'https://www.youtube.com/watch?v=JdD9PxIoDx8',
    rating: 1,
    keywords: ['Large Screen Ad', 'Running'],
  },
  {
    id: '5-07',
    category: 'Other',
    subcategory: 'Entertainment',
    region: 'China',
    robotType: 'PuduBot 2',
    clientName: 'KTV',
    videoUrl: 'https://youtu.be/1H65BMz9XuA',
    rating: 2,
    keywords: ['Delivery Mode', 'Birthday Mode'],
  },
  {
    id: '5-08',
    category: 'Other',
    subcategory: 'Entertainment',
    region: 'Australia',
    robotType: 'PuduBot 2',
    clientName: 'Racing Center',
    videoUrl: 'https://www.facebook.com/photo/?fbid=180091501437042&set=pcb.180091554770370',
    rating: 2,
    keywords: ['Running'],
  },
  {
    id: '5-09',
    category: 'Other',
    subcategory: 'Retail',
    region: 'France',
    robotType: 'KettyBot',
    clientName: 'Joueclub',
    videoUrl: '', // "KettyBot_JouéClub_France_01.mp4"
    rating: 2,
    keywords: ['Running'],
  },
  {
    id: '5-10',
    category: 'Other',
    subcategory: 'Entertainment',
    region: 'Russia',
    robotType: 'KettyBot',
    clientName: 'Monster Hills',
    videoUrl: 'https://www.youtube.com/watch?v=aC9KFjCZ_oA',
    rating: 1,
    keywords: ['Large Screen Ad', 'Running'],
  },
  {
    id: '5-11',
    category: 'Other',
    subcategory: 'Entertainment',
    region: 'Canada',
    robotType: 'KettyBot', // & Bella, PuduBot
    clientName: 'Xtreme Trampoline Park',
    videoUrl: 'https://youtu.be/KgPh6YxtmTk',
    rating: 4,
    keywords: ['Combo: Bella+PuduBot'],
  },
  {
    id: '5-12',
    category: 'Other',
    subcategory: 'Entertainment',
    region: 'Poland',
    robotType: 'BellaBot',
    clientName: 'Hula Park',
    videoUrl: 'https://drive.google.com/file/d/11ZzGCT3K6mLFbhLQ1Vpy7FRn4uN6LzZ9/view?usp=share_link',
    rating: 2,
    keywords: ['Sticker', 'Running'],
  },

  // --- 6. Cleaning (Page 15-16) ---
  {
    id: '6-01',
    category: 'Cleaning',
    subcategory: 'SH1',
    region: 'Global',
    robotType: 'SH1',
    clientName: 'Functional Demo - Oil Cleaning',
    videoUrl: 'https://drive.google.com/file/d/1aJW6LhU8AOaLyeoX-hXpyArhA3Y489_L/view?usp=share_link',
    rating: 5,
    keywords: ['Oil Cleaning'],
  },
  {
    id: '6-02',
    category: 'Cleaning',
    subcategory: 'SH1',
    region: 'Global',
    robotType: 'SH1',
    clientName: 'Functional Demo - Washing',
    videoUrl: 'https://drive.google.com/file/d/1eBrjkTRlxsmNaUJZaGGFPUzW2SySygZf/view?usp=share_link',
    rating: 5,
    keywords: ['Washing'],
  },
  {
    id: '6-03',
    category: 'Cleaning',
    subcategory: 'SH1',
    region: 'Global',
    robotType: 'SH1',
    clientName: 'Functional Demo - Slope',
    videoUrl: 'https://drive.google.com/file/d/1gkpLjev9MNRQnjXya8ICTt4U7DPyGO5r/view?usp=share_link',
    rating: 5,
    keywords: ['Slope Cleaning'],
  },
  {
    id: '6-04',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'Canada',
    robotType: 'CC1',
    clientName: 'Restaurant',
    videoUrl: '', // "restaurant3.mp4"
    rating: 4,
    keywords: ['Cement Tile'],
  },
  {
    id: '6-05',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'Russia',
    robotType: 'CC1',
    clientName: 'Supermarket',
    videoUrl: '', // "supermarket3.mp4"
    rating: 4,
    keywords: ['Fresh Area Water Stain'],
  },
  {
    id: '6-06',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'Russia',
    robotType: 'CC1',
    clientName: 'Parking Lot',
    videoUrl: '', // "workshop3.mp4"
    rating: 4,
    keywords: ['Cement Floor'],
  },
  {
    id: '6-07',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'China',
    robotType: 'CC1',
    clientName: 'Train Station',
    videoUrl: '', // "1668414006608.mp4"
    rating: 4,
    keywords: ['Marble Tile'],
  },
  {
    id: '6-08',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'Singapore',
    robotType: 'CC1',
    clientName: 'Airport',
    videoUrl: '', // "airport2.mp4"
    rating: 4,
    keywords: ['Carpet'],
  },
  {
    id: '6-09',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'Global',
    robotType: 'CC1',
    clientName: 'Retail',
    videoUrl: '', // "store 1.mp4"
    rating: 4,
    keywords: ['Marble Tile'],
  },
  {
    id: '6-10',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'Russia',
    robotType: 'CC1',
    clientName: 'Gym',
    videoUrl: '', // "gym2.mp4"
    rating: 4,
    keywords: ['Wood Floor'],
  },
  {
    id: '6-11',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'Japan',
    robotType: 'CC1',
    clientName: 'Office',
    videoUrl: '', // "office building4.mp4"
    rating: 4,
    keywords: ['Short Carpet'],
  },
  {
    id: '6-12',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'China',
    robotType: 'CC1',
    clientName: 'Office',
    videoUrl: '', // "office building5.mp4"
    rating: 4,
    keywords: ['Hard Floor', 'Coffee Stain'],
  },
  {
    id: '6-13',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'Russia',
    robotType: 'CC1',
    clientName: 'Bank',
    videoUrl: '', // "bank1.mp4"
    rating: 4,
    keywords: ['Hard Floor'],
  },
  {
    id: '6-14',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'Japan',
    robotType: 'CC1',
    clientName: 'Hospital',
    videoUrl: '', // "hospital1.mp4"
    rating: 4,
    keywords: ['Hard Floor', 'Corridor'],
  },
  {
    id: '6-15',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'Russia',
    robotType: 'CC1',
    clientName: 'Showroom',
    videoUrl: '', // "showroom3.mp4"
    rating: 4,
    keywords: ['Short Carpet'],
  },
  {
    id: '6-16',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'Costa Rica',
    robotType: 'CC1',
    clientName: 'Office',
    videoUrl: 'https://drive.google.com/drive/folders/1m1nlp0JIk5rRg1kn36QT2k_5cS0EIby-?usp=share_link',
    rating: 4,
    keywords: ['Wood Floor', 'Tile'],
  },
  {
    id: '6-17',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'China',
    robotType: 'CC1',
    clientName: 'Subway Station',
    videoUrl: 'https://drive.google.com/file/d/1ohkEl2LV9tnySCr3hD0y9Wlkylgu_xWf/view?usp=share_link',
    rating: 4,
    keywords: ['Marble Tile'],
  },
  {
    id: '6-18',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'China',
    robotType: 'CC1',
    clientName: 'School',
    videoUrl: 'https://youtu.be/FtAGFgwR7Rw',
    rating: 4,
    keywords: ['Hard Floor'],
  },
  {
    id: '6-19',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'Canada',
    robotType: 'CC1',
    clientName: 'Amusement Park',
    videoUrl: 'https://youtu.be/KgPh6YxtmTk',
    rating: 4,
    keywords: ['Interview', 'Combo'],
  },
];
