import { VideoCase } from './types';

export const INITIAL_DATA: VideoCase[] = [
  // --- 1. Product Promo ---
  {
    id: '101',
    category: 'Promo',
    subcategory: 'Product Series',
    region: 'Global',
    robotType: 'BellaBot',
    clientName: 'BellaBot Promo',
    videoUrl: 'https://www.youtube.com/watch?v=A6vH-QyBTIw',
    rating: 5,
    keywords: ['Promo'],
  },
  {
    id: '102',
    category: 'Promo',
    subcategory: 'Product Series',
    region: 'Global',
    robotType: 'KettyBot',
    clientName: 'KettyBot Promo',
    videoUrl: 'https://www.youtube.com/watch?v=-5-eIQben-M',
    rating: 5,
    keywords: ['Promo'],
  },
  {
    id: '103',
    category: 'Promo',
    subcategory: 'Product Series',
    region: 'Global',
    robotType: 'FlashBot',
    clientName: 'FlashBot Promo',
    videoUrl: 'https://www.youtube.com/watch?v=taICF8-mlRI',
    rating: 5,
    keywords: ['Promo'],
  },
  {
    id: '104',
    category: 'Promo',
    subcategory: 'Product Series',
    region: 'Global',
    robotType: 'PuduBot 2',
    clientName: 'PuduBot 2 Promo',
    videoUrl: 'https://www.youtube.com/watch?v=45vUOogXXQc',
    rating: 5,
    keywords: ['Promo'],
  },
  {
    id: '105',
    category: 'Promo',
    subcategory: 'Product Series',
    region: 'Global',
    robotType: 'PuduBot',
    clientName: 'PuduBot Promo',
    videoUrl: 'https://www.youtube.com/watch?v=u2LVIVOK_cs',
    rating: 5,
    keywords: ['Promo'],
  },
  {
    id: '106',
    category: 'Promo',
    subcategory: 'Product Series',
    region: 'Global',
    robotType: 'CC1',
    clientName: 'CC1 Promo',
    videoUrl: 'https://www.youtube.com/watch?v=qoYgbgU5HNI',
    rating: 5,
    keywords: ['Promo'],
  },
  {
    id: '107',
    category: 'Promo',
    subcategory: 'Product Series',
    region: 'Global',
    robotType: 'HolaBot',
    clientName: 'HolaBot Promo',
    videoUrl: 'https://www.youtube.com/watch?v=NR0ZO0CE7WQ',
    rating: 5,
    keywords: ['Promo'],
  },
  {
    id: '108',
    category: 'Promo',
    subcategory: 'Product Series',
    region: 'Global',
    robotType: 'FlashBot',
    clientName: 'FlashBot Box Promo',
    videoUrl: 'https://www.youtube.com/watch?v=ZhNCUcAWEYU',
    rating: 5,
    keywords: ['Promo'],
  },
  {
    id: '109',
    category: 'Promo',
    subcategory: 'Product Series',
    region: 'Global',
    robotType: 'SwiftBot',
    clientName: 'SwiftBot Promo',
    videoUrl: 'https://www.youtube.com/watch?v=iNQbSRE7AS0',
    rating: 5,
    keywords: ['Promo'],
  },
  {
    id: '110',
    category: 'Promo',
    subcategory: 'Product Series',
    region: 'Global',
    robotType: 'Puductor 2',
    clientName: 'Puductor 2 Promo',
    videoUrl: 'https://www.youtube.com/watch?v=KCXWGo9-qvQ',
    rating: 5,
    keywords: ['Promo'],
  },
  {
    id: '111',
    category: 'Promo',
    subcategory: 'IOT Series',
    region: 'Global',
    robotType: 'IOT',
    clientName: 'Pager - Office Scene',
    videoUrl: 'https://www.youtube.com/watch?v=9D0i8AK0kAM',
    rating: 4,
    keywords: ['IOT', 'Pager'],
  },
  {
    id: '112',
    category: 'Promo',
    subcategory: 'IOT Series',
    region: 'Global',
    robotType: 'IOT',
    clientName: 'Pager - Factory Scene',
    videoUrl: 'https://www.youtube.com/watch?v=bgk9svAuMcs',
    rating: 4,
    keywords: ['IOT', 'Pager'],
  },
  {
    id: '113',
    category: 'Promo',
    subcategory: 'IOT Series',
    region: 'Global',
    robotType: 'IOT',
    clientName: 'Menu Locator',
    videoUrl: 'https://www.youtube.com/watch?v=6mus8nV2Mtc',
    rating: 4,
    keywords: ['IOT', 'Menu Locator'],
  },

  // --- 2. Catering: Western ---
  {
    id: '201',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Ireland',
    robotType: 'BellaBot',
    clientName: "Pandini's",
    videoUrl: 'https://www.youtube.com/watch?v=auZKiihVqOw',
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '202',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Ireland',
    robotType: 'HolaBot',
    clientName: "Pandini's",
    videoUrl: 'https://drive.google.com/file/d/1gecgUZV_UPxsAatYjrGFoTa3N-kMcIUn/view?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '203',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Australia',
    robotType: 'KettyBot',
    clientName: 'Maldron Hotel Newcastle',
    videoUrl: 'https://www.youtube.com/watch?v=ZSPDLhoukF8',
    rating: 2,
    keywords: ['Delivery Mode', 'Large Screen Ad'],
  },
  {
    id: '204',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Austria',
    robotType: 'BellaBot',
    clientName: 'Rose',
    videoUrl: 'https://drive.google.com/file/d/1gecgUZV_UPxsAatYjrGFoTa3N-kMcIUn/view?usp=share_link',
    rating: 1,
    keywords: ['Sticker'],
  },
  {
    id: '205',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Austria',
    robotType: 'BellaBot',
    clientName: 'Seerestaurant Rosé',
    videoUrl: 'https://youtu.be/-chH0aheS5A',
    rating: 3,
    keywords: ['Running', 'Sticker', 'Semi-outdoor'],
  },
  {
    id: '206',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Poland',
    robotType: 'BellaBot',
    clientName: 'PizzaHut',
    videoUrl: 'https://drive.google.com/file/d/1wJ5K61o9332BaqYQpASyZfIbEhFORlkD/view?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode', 'Sticker'],
  },
  {
    id: '207',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Poland',
    robotType: 'BellaBot',
    clientName: 'KFC',
    videoUrl: 'https://drive.google.com/file/d/1VrVwXyXUvPoYGCPut_Q-AsfW0pyRcgG6/view?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode', 'Sticker'],
  },
  {
    id: '208',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Poland',
    robotType: 'BellaBot',
    clientName: 'Sztuka Restaurant',
    videoUrl: 'https://www.youtube.com/watch?v=DGajUN1icAs',
    rating: 2,
    keywords: ['Delivery Mode', 'Sticker'],
  },
  {
    id: '209',
    category: 'Catering',
    subcategory: 'Western',
    region: 'UAE',
    robotType: 'BellaBot',
    clientName: 'Dolci&Capricci',
    videoUrl: 'https://drive.google.com/file/d/1hovdSQjqPkjwnAkUkWlbInXvkQb6-Cxe/view?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode', 'Sticker'],
  },
  {
    id: '210',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Netherlands',
    robotType: 'BellaBot',
    clientName: "Momma's Restaurant",
    videoUrl: 'https://www.youtube.com/watch?v=6cNWc8TJoI4',
    rating: 2,
    keywords: ['Sticker', 'Delivery Mode'],
  },
  {
    id: '211',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Canada',
    robotType: 'BellaBot',
    clientName: "Denny's",
    videoUrl: 'https://youtu.be/l1hQ5YTMJEw',
    rating: 3,
    keywords: ['Sticker', 'Delivery Mode', 'Touch'],
  },
  {
    id: '212',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Croatia',
    robotType: 'BellaBot',
    clientName: 'Marché Mövenpick',
    videoUrl: 'https://www.youtube.com/watch?v=1tYEvbZJ6Xk',
    rating: 3,
    keywords: ['Delivery Mode', 'Sticker', 'Birthday Mode'],
  },
  {
    id: '213',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Malta',
    robotType: 'BellaBot',
    clientName: 'MONDO',
    videoUrl: 'https://www.youtube.com/watch?v=XgS2z6lrcgY',
    rating: 2,
    keywords: ['Sticker', 'Touch', 'Delivery Mode'],
  },
  {
    id: '214',
    category: 'Catering',
    subcategory: 'Western',
    region: 'USA',
    robotType: 'BellaBot',
    clientName: 'Magic Noodle',
    videoUrl: 'https://www.youtube.com/watch?v=lK8WSf3jN2I',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '215',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Mexico',
    robotType: 'BellaBot',
    clientName: 'LAS ALITAS',
    videoUrl: 'https://www.youtube.com/watch?v=_lw8G35Netw',
    rating: 1,
    keywords: ['Running'],
  },
  {
    id: '216',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Europe',
    robotType: 'BellaBot',
    clientName: 'PizzaHut',
    videoUrl: 'https://drive.google.com/file/d/1mpoCTj5T1MVTDeFz0FKHAc54TazDjVDl/view?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode', 'Sticker'],
  },
  {
    id: '217',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Europe',
    robotType: 'BellaBot',
    clientName: 'KFC',
    videoUrl: 'https://drive.google.com/file/d/13sDjmvFxadAOoWHM8OJwDibOzskINoV8/view?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode', 'Sticker'],
  },
  {
    id: '218',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Japan',
    robotType: 'BellaBot',
    clientName: 'Restaurant',
    videoUrl: 'https://www.youtube.com/watch?v=X-4PAdpVz9g',
    rating: 3,
    keywords: ['Sticker', 'Delivery Mode', 'Touch', 'Birthday Mode'],
  },
  {
    id: '219',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Japan',
    robotType: 'KettyBot',
    clientName: "Coco's Restaurant",
    videoUrl: 'https://www.youtube.com/shorts/FuDpJOGmUVc',
    rating: 4,
    keywords: ['Delivery Mode', 'Tray', 'Button', 'Ad'],
  },
  {
    id: '220',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Saudi Arabia',
    robotType: 'BellaBot',
    clientName: 'South Grandstand (F1)',
    videoUrl: 'https://drive.google.com/file/d/1Iz_1m0hzLmjhRb8J4T4BdZf_sCh9ePJJ/view?usp=share_link',
    rating: 1,
    keywords: ['Sticker', 'Running'],
  },
  {
    id: '221',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Slovenia',
    robotType: 'BellaBot',
    clientName: "McDonald's",
    videoUrl: 'https://drive.google.com/drive/folders/1ZEUq_IWmJiWPk6wMuv0-0KIr2hGLeWXX?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode', 'Sticker'],
  },
  {
    id: '222',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Taiwan',
    robotType: 'BellaBot',
    clientName: 'Britishake',
    videoUrl: 'https://youtu.be/ny5LYHfwaWQ',
    rating: 3,
    keywords: ['Running', 'Sticker'],
  },
  {
    id: '223',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Spain',
    robotType: 'BellaBot',
    clientName: 'Comic Planet',
    videoUrl: 'https://www.youtube.com/watch?v=s4fwPwKqLVY',
    rating: 2,
    keywords: ['Sticker', 'Delivery Mode'],
  },
  {
    id: '224',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Spain',
    robotType: 'BellaBot',
    clientName: 'LA CHANCHA',
    videoUrl: 'https://www.youtube.com/watch?v=q4Q0e5c-t1E',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '225',
    category: 'Catering',
    subcategory: 'Western',
    region: 'New Zealand',
    robotType: 'BellaBot',
    clientName: "Andy's Burgers & Bar",
    videoUrl: 'https://drive.google.com/file/d/1tYLQjae0pLMeJZ0MJEapOx8zuJPp8SaY/view?usp=share_link',
    rating: 3,
    keywords: ['Sticker', 'Delivery Mode'],
  },
  {
    id: '226',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Italy',
    robotType: 'BellaBot',
    clientName: 'Kiyomi',
    videoUrl: 'https://drive.google.com/file/d/1BpDZgTVttlKAk6ZrdjjTs9Z0zmk6cYaw/view?usp=share_link',
    rating: 3,
    keywords: ['Delivery Mode', 'Birthday Mode', 'Dish Return', 'Touch'],
  },
  {
    id: '227',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Italy',
    robotType: 'BellaBot',
    clientName: 'Ristorante FuoriCittà Pizzeria',
    videoUrl: 'https://www.youtube.com/watch?v=Kc4z4MNYoX8',
    rating: 2,
    keywords: ['Delivery Mode', 'Sticker'],
  },
  {
    id: '228',
    category: 'Catering',
    subcategory: 'Western',
    region: 'Italy',
    robotType: 'BellaBot',
    clientName: 'Casa',
    videoUrl: 'https://www.youtube.com/watch?v=YqpGTt_rY2Q',
    rating: 1,
    keywords: ['Running'],
  },

  // --- 2. Catering: Japanese/Korean ---
  {
    id: '301',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'South Korea',
    robotType: 'PuduBot',
    clientName: 'Korean Restaurant',
    videoUrl: '', // Link broken in source or generic
    rating: 2,
    keywords: ['Delivery Mode', 'Running'],
  },
  {
    id: '302',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'Canada',
    robotType: 'BellaBot',
    clientName: '168 Sushi',
    videoUrl: 'https://www.youtube.com/watch?v=AOGbJ_0znTg',
    rating: 2,
    keywords: ['Delivery Mode', 'Birthday Mode'],
  },
  {
    id: '303',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'Malaysia',
    robotType: 'BellaBot',
    clientName: 'Sweetree',
    videoUrl: 'https://www.youtube.com/watch?v=L0aLoLQC6VI',
    rating: 2,
    keywords: ['Running'],
  },
  {
    id: '304',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'Malaysia',
    robotType: 'KettyBot',
    clientName: 'Nippon Sushi',
    videoUrl: 'https://www.youtube.com/watch?v=SBZAxtXOpJI',
    rating: 2,
    keywords: ['Delivery Mode', 'Large Screen Ad'],
  },
  {
    id: '305',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'Malaysia',
    robotType: 'KettyBot',
    clientName: 'Kawa Japanese Restaurant',
    videoUrl: 'https://www.youtube.com/watch?v=G4myzc0-SVo',
    rating: 2,
    keywords: ['Delivery Mode', 'Large Screen Ad'],
  },
  {
    id: '306',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'USA',
    robotType: 'BellaBot',
    clientName: 'Sakura Japanese Resterant',
    videoUrl: 'https://drive.google.com/file/d/1MoM5yqt-6RMmaW0VAWMe6IcWyCF7TMFE/view?usp=share_link',
    rating: 2,
    keywords: ['Touch', 'Delivery Mode'],
  },
  {
    id: '307',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'USA',
    robotType: 'BellaBot',
    clientName: 'Yama Sushi',
    videoUrl: 'https://www.youtube.com/watch?v=Z_bgBK4Ap20',
    rating: 1,
    keywords: ['Running'],
  },
  {
    id: '308',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'USA',
    robotType: 'KettyBot',
    clientName: 'Hanu K BBQ',
    videoUrl: 'https://www.youtube.com/watch?v=EXPyNKSvs1s',
    rating: 1,
    keywords: ['Large Screen Ad', 'Running'],
  },
  {
    id: '309',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'USA',
    robotType: 'KettyBot',
    clientName: 'FuGaKyu',
    videoUrl: 'https://www.youtube.com/shorts/Es4x0dDkk-Y',
    rating: 1,
    keywords: ['Running', 'Large Screen Ad'],
  },
  {
    id: '310',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'Norway',
    robotType: 'KettyBot',
    clientName: 'Chimak House',
    videoUrl: 'https://www.youtube.com/watch?v=3V2i6BlxvHU',
    rating: 2,
    keywords: ['Delivery Mode', 'Large Screen Ad'],
  },
  {
    id: '311',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'Japan',
    robotType: 'BellaBot',
    clientName: 'Japanese Restaurant',
    videoUrl: 'https://www.youtube.com/watch?v=P6SRXykBnIc',
    rating: 2,
    keywords: ['Delivery Mode', 'Touch'],
  },
  {
    id: '312',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'Japan',
    robotType: 'BellaBot',
    clientName: 'Watami',
    videoUrl: 'https://www.youtube.com/watch?v=bGlRz6Z4CxE',
    rating: 2,
    keywords: ['Delivery Mode', 'Touch'],
  },
  {
    id: '313',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'Japan',
    robotType: 'HolaBot',
    clientName: 'Kyushu Station Hotel Kokura',
    videoUrl: 'https://youtu.be/Y6783XWLkTY',
    rating: 3,
    keywords: ['Watch', 'Dish Return Mode'],
  },
  {
    id: '314',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'Japan',
    robotType: 'KettyBot',
    clientName: 'Yakiniku Bugyo',
    videoUrl: 'https://www.youtube.com/watch?v=D3kH-77MGQM',
    rating: 3,
    keywords: ['Large Screen Ad', 'Tray', 'Running'],
  },
  {
    id: '315',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'Taiwan',
    robotType: 'BellaBot',
    clientName: 'Carbon',
    videoUrl: 'https://drive.google.com/file/d/1XIAPnYOcrSyo53b5GpzCOxwZz529lgeb/view?usp=share_link',
    rating: 2,
    keywords: ['Sticker'],
  },
  {
    id: '316',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'Spain',
    robotType: 'BellaBot',
    clientName: 'Flower Wood',
    videoUrl: 'https://drive.google.com/file/d/1ut8Q-4PJIbu083FSIhplGHCUHgx44sjS/view?usp=share_link',
    rating: 2,
    keywords: ['Touch', 'Delivery Mode'],
  },
  {
    id: '317',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'Spain',
    robotType: 'PuduBot',
    clientName: 'Sakura Restaurante',
    videoUrl: 'https://www.youtube.com/watch?v=14FMToh0rLM',
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '318',
    category: 'Catering',
    subcategory: 'Japanese/Korean',
    region: 'UK',
    robotType: 'KettyBot',
    clientName: 'Gami Chicken',
    videoUrl: 'https://www.youtube.com/shorts/81dgWbi_BTU',
    rating: 1,
    keywords: ['Running'],
  },

  // --- 2. Catering: Fast Food ---
  {
    id: '401',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'Australia',
    robotType: 'PuduBot',
    clientName: "Dougie's Grill",
    videoUrl: '', 
    rating: 1,
    keywords: ['Delivery Mode', 'Running'],
  },
  {
    id: '402',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'Poland',
    robotType: 'KettyBot',
    clientName: 'Da Grasso',
    videoUrl: 'https://www.youtube.com/watch?v=t8gxwkESYlo',
    rating: 3,
    keywords: ['Delivery Mode', 'Large Screen Ad'],
  },
  {
    id: '403',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'Poland',
    robotType: 'KettyBot',
    clientName: 'Da Grasso Pizza',
    videoUrl: 'https://drive.google.com/drive/folders/1WBz6Ezn9UuXaCUIHjpmYQ3OdXF3Wrz3V?usp=share_link',
    rating: 1,
    keywords: ['Delivery Mode', 'Large Screen Ad', 'Sticker'],
  },
  {
    id: '404',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'Russia',
    robotType: 'PuduBot',
    clientName: 'Restaurant',
    videoUrl: '',
    rating: 2,
    keywords: ['Delivery Mode', 'Running'],
  },
  {
    id: '405',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'Russia',
    robotType: 'PuduBot',
    clientName: 'Pizza Factory',
    videoUrl: '',
    rating: 2,
    keywords: ['Delivery Mode', 'Running'],
  },
  {
    id: '406',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'Costa Rica',
    robotType: 'KettyBot',
    clientName: 'Burger King',
    videoUrl: 'https://drive.google.com/drive/folders/1IjglqzyP4JUD5kHtaOgXghOxQa4afOr7?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode', 'Large Screen Ad', 'Sticker'],
  },
  {
    id: '407',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'South Korea',
    robotType: 'PuduBot',
    clientName: 'Texas BBQ',
    videoUrl: '',
    rating: 2,
    keywords: ['Delivery Mode', 'Sticker'],
  },
  {
    id: '408',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'Canada',
    robotType: 'KettyBot',
    clientName: 'Burger King',
    videoUrl: 'https://drive.google.com/file/d/1fNdqNglig8ryPAiv_b1xnDSZsL_ksZL9/view?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode', 'Large Screen Ad'],
  },
  {
    id: '409',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'Canada',
    robotType: 'PuduBot 2',
    clientName: "Denny's",
    videoUrl: 'https://youtu.be/V9Q4rXYuAco',
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '410',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'Malaysia',
    robotType: 'PuduBot',
    clientName: 'Bistro',
    videoUrl: 'https://youtu.be/QJGGxbMhIHI',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '411',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'USA',
    robotType: 'KettyBot',
    clientName: 'Avantis Ristorante',
    videoUrl: 'https://www.facebook.com/watch/?v=398290171901873',
    rating: 3,
    keywords: ['Host Mode', 'Large Screen Ad', 'Delivery Mode'],
  },
  {
    id: '412',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'USA',
    robotType: 'PuduBot',
    clientName: 'Chicken-fil-a',
    videoUrl: 'https://youtu.be/t1sQoylLX9s',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '413',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'Saudi Arabia',
    robotType: 'PuduBot',
    clientName: 'Restaurant',
    videoUrl: 'https://youtube.com/shorts/tzUmSw8EpgA?feature=share',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '414',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'Guatemala',
    robotType: 'KettyBot',
    clientName: 'KFC',
    videoUrl: 'https://drive.google.com/drive/folders/1wN6XpirgL1gEut23TRXI9Mg3Pg5JKAhX?usp=share_link',
    rating: 3,
    keywords: ['Delivery Mode', 'Sticker', 'Large Screen Ad'],
  },
  {
    id: '415',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'New Zealand',
    robotType: 'BellaBot',
    clientName: 'TVNZ',
    videoUrl: 'https://www.youtube.com/watch?v=_e41k94lrLc',
    rating: 2,
    keywords: ['Running'],
  },
  {
    id: '416',
    category: 'Catering',
    subcategory: 'Fast Food',
    region: 'Chile',
    robotType: 'BellaBot',
    clientName: "McDonald's",
    videoUrl: 'https://drive.google.com/drive/folders/1UNHPHw5RkowdhzRGIELQ5-tRa2lpLjMB?usp=share_link',
    rating: 1,
    keywords: ['Delivery Mode'],
  },

  // --- 2. Catering: Hotpot ---
  {
    id: '501',
    category: 'Catering',
    subcategory: 'Hotpot',
    region: 'Malaysia',
    robotType: 'PuduBot 2',
    clientName: 'Akagui',
    videoUrl: 'https://youtube.com/shorts/qS0GzEYo6NE?feature=share',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '502',
    category: 'Catering',
    subcategory: 'Hotpot',
    region: 'USA',
    robotType: 'PuduBot',
    clientName: 'Haidilao',
    videoUrl: '',
    rating: 1,
    keywords: ['Birthday Mode'],
  },
  {
    id: '503',
    category: 'Catering',
    subcategory: 'Hotpot',
    region: 'Japan',
    robotType: 'BellaBot',
    clientName: 'SYABU-YO',
    videoUrl: 'https://youtu.be/4VIr-XfGZww',
    rating: 3,
    keywords: ['Running'],
  },
  {
    id: '504',
    category: 'Catering',
    subcategory: 'Hotpot',
    region: 'Thailand',
    robotType: 'BellaBot',
    clientName: 'You&I Premium Suki Buffet',
    videoUrl: 'https://www.youtube.com/watch?v=Xr0KS7TJOak',
    rating: 3,
    keywords: ['Running', 'Delivery Mode', 'Decoration'],
  },
  {
    id: '505',
    category: 'Catering',
    subcategory: 'Hotpot',
    region: 'Spain',
    robotType: 'BellaBot',
    clientName: 'Liuyishou',
    videoUrl: 'https://drive.google.com/file/d/1fJH7-fbaqk7bzVWATiH6lEkSnT11NFa3/view?usp=share_link',
    rating: 3,
    keywords: ['Delivery Mode', 'Sticker', 'Touch'],
  },
  {
    id: '506',
    category: 'Catering',
    subcategory: 'Hotpot',
    region: 'Spain',
    robotType: 'BellaBot',
    clientName: 'Mala Wuqing',
    videoUrl: 'https://drive.google.com/file/d/1vy4g6JHcebQIjjgCQiR3OHtRWBVuh77D/view?usp=share_link',
    rating: 2,
    keywords: ['Sticker', 'Delivery Mode'],
  },
  {
    id: '507',
    category: 'Catering',
    subcategory: 'Hotpot',
    region: 'Singapore',
    robotType: 'HolaBot',
    clientName: 'Black Knight Hotpot',
    videoUrl: 'https://youtube.com/shorts/xy7vUDMo8sg?feature=share',
    rating: 1,
    keywords: ['Dish Return'],
  },
  {
    id: '508',
    category: 'Catering',
    subcategory: 'Hotpot',
    region: 'China',
    robotType: 'BellaBot',
    clientName: 'Yemei Hotpot',
    videoUrl: 'https://www.youtube.com/watch?v=G8xwfyZPc6I',
    rating: 3,
    keywords: ['Sticker', 'Delivery Mode'],
  },
  {
    id: '509',
    category: 'Catering',
    subcategory: 'Hotpot',
    region: 'China',
    robotType: 'PuduBot',
    clientName: 'Haidilao',
    videoUrl: 'https://youtube.com/shorts/-JX71GmD2pA?feature=share',
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '510',
    category: 'Catering',
    subcategory: 'Hotpot',
    region: 'China',
    robotType: 'PuduBot',
    clientName: 'Haidilao',
    videoUrl: 'https://www.youtube.com/watch?v=x60mwsl_Kmk',
    rating: 3,
    keywords: ['Delivery Mode'],
  },

  // --- 2. Catering: Cafe ---
  {
    id: '601',
    category: 'Catering',
    subcategory: 'Cafe',
    region: 'Poland',
    robotType: 'BellaBot',
    clientName: 'Shell Café',
    videoUrl: 'https://drive.google.com/drive/folders/1-0woy1ziRmneOulgD6aWsW4ubdl7nB97?usp=share_link',
    rating: 1,
    keywords: ['Skin'],
  },
  {
    id: '602',
    category: 'Catering',
    subcategory: 'Cafe',
    region: 'Germany',
    robotType: 'BellaBot',
    clientName: 'Moness Coffee',
    videoUrl: 'https://www.youtube.com/watch?v=fW0e_E48iFA',
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '603',
    category: 'Catering',
    subcategory: 'Cafe',
    region: 'Japan',
    robotType: 'BellaBot',
    clientName: 'Starbucks',
    videoUrl: 'https://drive.google.com/file/d/1eqhz9PiMxl2xXCUj9-vojoOGdM4OHBBr/view?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode', 'Cover'],
  },
  {
    id: '604',
    category: 'Catering',
    subcategory: 'Cafe',
    region: 'Malaysia',
    robotType: 'PuduBot',
    clientName: 'TNL Bakery Cafe',
    videoUrl: 'https://fb.watch/jy4DxztMhc/',
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '605',
    category: 'Catering',
    subcategory: 'Cafe',
    region: 'Malaysia',
    robotType: 'PuduBot',
    clientName: 'Toast N Toast',
    videoUrl: 'https://youtu.be/dGifpvv6s8E',
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '606',
    category: 'Catering',
    subcategory: 'Cafe',
    region: 'Malaysia',
    robotType: 'PuduBot',
    clientName: 'Salam 1 Cafe',
    videoUrl: 'https://youtu.be/Ez8S4diZVWA',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '607',
    category: 'Catering',
    subcategory: 'Cafe',
    region: 'Malaysia',
    robotType: 'PuduBot',
    clientName: 'Tal Cafe',
    videoUrl: 'https://youtu.be/90dBLTwX-UQ',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '608',
    category: 'Catering',
    subcategory: 'Cafe',
    region: 'Malaysia',
    robotType: 'PuduBot',
    clientName: '42 Zest Cafe',
    videoUrl: 'https://youtu.be/4mTl-yi1l2g',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '609',
    category: 'Catering',
    subcategory: 'Cafe',
    region: 'USA',
    robotType: 'KettyBot',
    clientName: "Dunkin' Donuts",
    videoUrl: 'https://www.facebook.com/zpeedy.gonzales/videos/714301536506230/',
    rating: 2,
    keywords: ['Delivery Mode', 'Large Screen Ad'],
  },
  {
    id: '610',
    category: 'Catering',
    subcategory: 'Cafe',
    region: 'Switzerland',
    robotType: 'BellaBot',
    clientName: 'Coffee Island',
    videoUrl: 'https://drive.google.com/file/d/1wg6Lb0rO68x8oCXKrPqcpqBuiZaUjvO6/view?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode', 'Skin'],
  },
  {
    id: '611',
    category: 'Catering',
    subcategory: 'Cafe',
    region: 'India',
    robotType: 'BellaBot',
    clientName: 'Rasa Koffie',
    videoUrl: 'https://drive.google.com/file/d/1DAlJiVjekC_34DDOLaf98xRSEOHJzwSw/view?usp=share_link',
    rating: 1,
    keywords: ['Delivery Mode'],
  },

  // --- 2. Catering: Chinese ---
  {
    id: '701',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'Australia',
    robotType: 'KettyBot',
    clientName: 'Authentic Bites Dumpling House',
    videoUrl: 'https://www.youtube.com/watch?v=8fjDbUlOP4k',
    rating: 3,
    keywords: ['Delivery Mode', 'Scan Order'],
  },
  {
    id: '702',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'Australia',
    robotType: 'PuduBot',
    clientName: "MR Su's",
    videoUrl: '',
    rating: 2,
    keywords: ['Sticker'],
  },
  {
    id: '703',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'Canada',
    robotType: 'BellaBot',
    clientName: 'Golden Ocean Seafood Restaurant',
    videoUrl: 'https://drive.google.com/file/d/1mG4GMI9QVTOVwAIpf3G7AuoKDB7-gZzW/view?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '704',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'Malaysia',
    robotType: 'KettyBot',
    clientName: 'Ding Tai Feng',
    videoUrl: 'https://www.youtube.com/watch?v=gtsZXq_SNtE',
    rating: 2,
    keywords: ['Large Screen Ad', 'Running'],
  },
  {
    id: '705',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'Malaysia',
    robotType: 'KettyBot',
    clientName: 'YINZO KOPI',
    videoUrl: 'https://www.youtube.com/watch?v=seAX15R9Cx0',
    rating: 2,
    keywords: ['Delivery Mode', 'Large Screen Ad', 'Tray'],
  },
  {
    id: '706',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'USA',
    robotType: 'HolaBot',
    clientName: 'Sapporo',
    videoUrl: '',
    rating: 1,
    keywords: ['Dish Return'],
  },
  {
    id: '707',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'USA',
    robotType: 'PuduBot',
    clientName: 'Dim Sum',
    videoUrl: '',
    rating: 2,
    keywords: ['Birthday Mode', 'Sticker'],
  },
  {
    id: '708',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'Saudi Arabia',
    robotType: 'BellaBot',
    clientName: 'Yunnan SILK ROAD Restaurant',
    videoUrl: 'https://www.youtube.com/watch?v=uT0Lpsm9LJI',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '709',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'Taiwan',
    robotType: 'BellaBot',
    clientName: 'Tim Ho Wan',
    videoUrl: 'https://www.youtube.com/watch?v=HnzozEbvjFY',
    rating: 1,
    keywords: ['Running', 'Sticker'],
  },
  {
    id: '710',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'Taiwan',
    robotType: 'HolaBot',
    clientName: 'Din Tai Fung',
    videoUrl: '',
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '711',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'Hong Kong',
    robotType: 'KettyBot',
    clientName: 'BTW',
    videoUrl: 'https://www.youtube.com/watch?v=HaKVZ4CfAtg',
    rating: 4,
    keywords: ['Host Mode', 'Delivery Mode', 'Birthday Mode', 'Cover', 'Tray', 'Sticker'],
  },
  {
    id: '712',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'Hong Kong',
    robotType: 'KettyBot',
    clientName: "Oliver's Super Sandwiches",
    videoUrl: 'https://www.youtube.com/watch?v=iYanRKFk1DA',
    rating: 3,
    keywords: ['Delivery Mode', 'Cover', 'Large Screen Ad', 'Button'],
  },
  {
    id: '713',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'Singapore',
    robotType: 'BellaBot',
    clientName: 'Putien',
    videoUrl: 'https://www.youtube.com/shorts/LYx1FmnPwaU',
    rating: 1,
    keywords: ['Running'],
  },
  {
    id: '714',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'Singapore',
    robotType: 'PuduBot',
    clientName: 'Swee Choon Tim Sum',
    videoUrl: 'https://youtu.be/pSi5qgqOeno',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '715',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'Indonesia',
    robotType: 'BellaBot',
    clientName: 'Imperial Kitchen & Dimsum',
    videoUrl: 'https://www.youtube.com/watch?v=L34-b4ws-iE',
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '716',
    category: 'Catering',
    subcategory: 'Chinese',
    region: 'UK',
    robotType: 'BellaBot',
    clientName: 'TCB Restaurant',
    videoUrl: 'https://www.youtube.com/watch?v=VarpXXEZHbk',
    rating: 2,
    keywords: ['Delivery Mode', 'Running'],
  },

  // --- 2. Catering: Southeast Asian ---
  {
    id: '801',
    category: 'Catering',
    subcategory: 'Southeast Asian',
    region: 'Australia',
    robotType: 'PuduBot',
    clientName: 'Indian Restaurant',
    videoUrl: '',
    rating: 2,
    keywords: ['Delivery Mode', 'Multi-table'],
  },
  {
    id: '802',
    category: 'Catering',
    subcategory: 'Southeast Asian',
    region: 'Canada',
    robotType: 'KettyBot',
    clientName: 'Mekong Asian Cuisine',
    videoUrl: 'https://www.youtube.com/watch?v=je8qPq1vBx4',
    rating: 4,
    keywords: ['Delivery Mode', 'Large Screen Ad', 'Birthday Mode'],
  },
  {
    id: '803',
    category: 'Catering',
    subcategory: 'Southeast Asian',
    region: 'Malaysia',
    robotType: 'BellaBot',
    clientName: "Johnny's Restaurant",
    videoUrl: 'https://www.youtube.com/watch?v=cvij8TLwhdY',
    rating: 3,
    keywords: ['Sticker', 'Delivery Mode'],
  },
  {
    id: '804',
    category: 'Catering',
    subcategory: 'Southeast Asian',
    region: 'Malaysia',
    robotType: 'BellaBot',
    clientName: 'Gegey',
    videoUrl: 'https://drive.google.com/file/d/1G-6SMOHMLx9EY6r_lFNImIYQ4hVBg02A/view?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode', 'Sticker'],
  },
  {
    id: '805',
    category: 'Catering',
    subcategory: 'Southeast Asian',
    region: 'Malaysia',
    robotType: 'BellaBot',
    clientName: 'Black Canyon',
    videoUrl: 'https://youtu.be/f_LE_vvFqVU',
    rating: 3,
    keywords: ['Running', 'Sticker'],
  },
  {
    id: '806',
    category: 'Catering',
    subcategory: 'Southeast Asian',
    region: 'Malaysia',
    robotType: 'PuduBot',
    clientName: 'Beng Huat Asam Fish Chicken Rice',
    videoUrl: 'https://fb.watch/jy4lN9bntq/',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '807',
    category: 'Catering',
    subcategory: 'Southeast Asian',
    region: 'Malaysia',
    robotType: 'PuduBot',
    clientName: 'Ichiban Ramen',
    videoUrl: 'https://youtu.be/j-1-SlbtR_g',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '808',
    category: 'Catering',
    subcategory: 'Southeast Asian',
    region: 'Malaysia',
    robotType: 'PuduBot',
    clientName: 'Style Food Court Bukit Mertajam',
    videoUrl: 'https://youtu.be/cdrDi4_XaOk',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '809',
    category: 'Catering',
    subcategory: 'Southeast Asian',
    region: 'Malaysia',
    robotType: 'PuduBot',
    clientName: 'Lee Noodle',
    videoUrl: 'https://youtu.be/Irrf-yA9XCM',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '810',
    category: 'Catering',
    subcategory: 'Southeast Asian',
    region: 'Malaysia',
    robotType: 'PuduBot',
    clientName: 'Restoran Ahmad Khan',
    videoUrl: 'https://youtu.be/dY_ljNKLYC0',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '811',
    category: 'Catering',
    subcategory: 'Southeast Asian',
    region: 'Malaysia',
    robotType: 'PuduBot 2',
    clientName: 'Y&Y Restaurant',
    videoUrl: 'https://www.facebook.com/secure.robotics.malaysia/videos/539845578298742',
    rating: 3,
    keywords: ['Delivery Mode', 'Cover'],
  },
  {
    id: '812',
    category: 'Catering',
    subcategory: 'Southeast Asian',
    region: 'USA',
    robotType: 'KettyBot',
    clientName: 'Pholicious',
    videoUrl: 'https://www.youtube.com/watch?v=rl_4UtXMz8g',
    rating: 1,
    keywords: ['Running'],
  },
  {
    id: '813',
    category: 'Catering',
    subcategory: 'Southeast Asian',
    region: 'Hong Kong',
    robotType: 'PuduBot',
    clientName: 'Saravanna Bhavan',
    videoUrl: 'https://youtube.com/shorts/c0TLYiTx7jw?feature=share',
    rating: 1,
    keywords: ['Delivery Mode'],
  },

  // --- 2. Catering: Hotel/Dessert/Middle Eastern ---
  {
    id: '901',
    category: 'Catering',
    subcategory: 'Hotel Restaurant',
    region: 'Ireland',
    robotType: 'BellaBot',
    clientName: 'Nevins Newfield Inn',
    videoUrl: 'https://youtu.be/Tq4wb7KfSvA',
    rating: 3,
    keywords: ['Running'],
  },
  {
    id: '902',
    category: 'Catering',
    subcategory: 'Hotel Restaurant',
    region: 'Poland',
    robotType: 'BellaBot',
    clientName: 'Elements',
    videoUrl: 'https://www.youtube.com/watch?v=2mN5_BBFMMw',
    rating: 3,
    keywords: ['Delivery Mode', 'Host Mode'],
  },
  {
    id: '903',
    category: 'Catering',
    subcategory: 'Hotel Restaurant',
    region: 'Poland',
    robotType: 'BellaBot',
    clientName: 'Marriott Warsaw Hotel',
    videoUrl: 'https://drive.google.com/file/d/1kQwEcj6CJYDIo5JlUISoET_aQLhOQ1VP/view?usp=share_link',
    rating: 2,
    keywords: ['Sticker', 'Delivery Mode'],
  },
  {
    id: '904',
    category: 'Catering',
    subcategory: 'Hotel Restaurant',
    region: 'Poland',
    robotType: 'BellaBot',
    clientName: 'Hotelu O3',
    videoUrl: 'https://www.youtube.com/watch?v=KZ644p7VAg8',
    rating: 4,
    keywords: ['Touch', 'IOT Automatic Door'],
  },
  {
    id: '905',
    category: 'Catering',
    subcategory: 'Hotel Restaurant',
    region: 'Poland',
    robotType: 'HolaBot',
    clientName: 'Cottonina Hotel',
    videoUrl: 'https://www.youtube.com/watch?v=DobG2n6lua4',
    rating: 2,
    keywords: ['Delivery Mode', 'Dish Return'],
  },
  {
    id: '906',
    category: 'Catering',
    subcategory: 'Hotel Restaurant',
    region: 'Japan',
    robotType: 'HolaBot',
    clientName: 'Torrent',
    videoUrl: 'https://youtu.be/K_g1fvA5UJo',
    rating: 3,
    keywords: ['Watch', 'Dish Return'],
  },
  {
    id: '907',
    category: 'Catering',
    subcategory: 'Hotel Restaurant',
    region: 'Hong Kong',
    robotType: 'BellaBot',
    clientName: 'Wetland Seasons Park',
    videoUrl: 'https://youtu.be/sDm8Xpe6IbE',
    rating: 2,
    keywords: ['Sticker', 'Running'],
  },
  {
    id: '908',
    category: 'Catering',
    subcategory: 'Hotel Restaurant',
    region: 'Hong Kong',
    robotType: 'FlashBot',
    clientName: 'Alva Hotel',
    videoUrl: 'https://youtu.be/o2fBnMtlE7Y',
    rating: 3,
    keywords: ['Delivery Mode', 'Sticker', 'Combo'],
  },
  {
    id: '909',
    category: 'Catering',
    subcategory: 'Hotel Restaurant',
    region: 'Singapore',
    robotType: 'BellaBot',
    clientName: 'Shangri-La Hotel',
    videoUrl: 'https://www.youtube.com/watch?v=wMvX6ikyKeY',
    rating: 2,
    keywords: ['Sticker', 'Dish Return'],
  },
  {
    id: '910',
    category: 'Catering',
    subcategory: 'Dessert Shop',
    region: 'Germany',
    robotType: 'BellaBot',
    clientName: 'Giovanni L.',
    videoUrl: 'https://www.youtube.com/watch?v=75AiJPhXVvM',
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '911',
    category: 'Catering',
    subcategory: 'Dessert Shop',
    region: 'Germany',
    robotType: 'HolaBot',
    clientName: 'Giovanni',
    videoUrl: 'https://youtu.be/jk3s-a5SQmU',
    rating: 2,
    keywords: ['Combo: Bella+Hola'],
  },
  {
    id: '912',
    category: 'Catering',
    subcategory: 'Middle Eastern',
    region: 'Dubai',
    robotType: 'BellaBot',
    clientName: 'Good food',
    videoUrl: 'https://www.youtube.com/watch?v=AMBf9fdXHkA',
    rating: 2,
    keywords: ['Sticker', 'Birthday Mode', 'Delivery Mode'],
  },
  {
    id: '913',
    category: 'Catering',
    subcategory: 'Middle Eastern',
    region: 'UAE',
    robotType: 'BellaBot',
    clientName: 'B-cafe',
    videoUrl: 'https://www.youtube.com/shorts/clPLt_tX4S8',
    rating: 2,
    keywords: ['Sticker', 'Running'],
  },
  {
    id: '914',
    category: 'Catering',
    subcategory: 'Middle Eastern',
    region: 'Netherlands',
    robotType: 'HolaBot',
    clientName: 'Landal Coldenhove',
    videoUrl: 'https://youtu.be/t2otX-pT6mQ',
    rating: 2,
    keywords: ['Combo: Bella+Hola'],
  },
  {
    id: '915',
    category: 'Catering',
    subcategory: 'Middle Eastern',
    region: 'Kuwait',
    robotType: 'BellaBot',
    clientName: 'Lebanese Restaurant',
    videoUrl: 'https://drive.google.com/file/d/1ABThT-soCn-sdhmUkSjJQoV6v7dQFEQo/view?usp=share_link',
    rating: 2,
    keywords: ['Delivery Mode', 'Host Mode'],
  },

  // --- 3. Retail: Supermarket ---
  {
    id: '1001',
    category: 'Retail',
    subcategory: 'Supermarket',
    region: 'Andorra',
    robotType: 'BellaBot',
    clientName: 'Carrefour (Coca Cola)',
    videoUrl: 'https://drive.google.com/drive/folders/1Bzi0PIe9hwIAi4Au9F8ObUr5H5Dif3-v?usp=share_link',
    rating: 3,
    keywords: ['Sticker', 'Running', 'Tray Rack'],
  },
  {
    id: '1002',
    category: 'Retail',
    subcategory: 'Supermarket',
    region: 'Chile',
    robotType: 'KettyBot',
    clientName: 'Walmart',
    videoUrl: 'https://drive.google.com/drive/folders/1ETjyJ9LqED58uEHgjGdVvZxsjKDt_pBS?usp=share_link',
    rating: 3,
    keywords: ['Sticker', 'Large Screen Ad'],
  },
  {
    id: '1003',
    category: 'Retail',
    subcategory: 'Supermarket',
    region: 'Guyana',
    robotType: 'KettyBot',
    clientName: 'Guía en supermercado',
    videoUrl: 'https://drive.google.com/file/d/1jwXfXe8CXj_E71HR4Pd_K7BdbHqVcwLW/view?usp=share_link',
    rating: 3,
    keywords: ['Guide', 'Large Screen Ad', 'Cruise Mode'],
  },
  {
    id: '1004',
    category: 'Retail',
    subcategory: 'Supermarket',
    region: 'Taiwan',
    robotType: 'BellaBot',
    clientName: 'Carrefour',
    videoUrl: 'https://drive.google.com/drive/folders/1iCO2Jj3KQL46x9f4KyTKO4dwfFD8Kgu7?usp=share_link',
    rating: 2,
    keywords: ['Sticker', 'Running'],
  },
  {
    id: '1005',
    category: 'Retail',
    subcategory: 'Supermarket',
    region: 'Thailand',
    robotType: 'BellaBot',
    clientName: 'Gourmet Market',
    videoUrl: 'https://drive.google.com/file/d/1Au71WGEn3JC6P8QCAX84yJqPuINaYrhf/view?usp=share_link',
    rating: 2,
    keywords: ['Sticker', 'Running'],
  },
  {
    id: '1006',
    category: 'Retail',
    subcategory: 'Supermarket',
    region: 'USA',
    robotType: 'KettyBot',
    clientName: 'Walmart',
    videoUrl: 'https://drive.google.com/drive/folders/1F7v1cZbIF7rPQwMJ2ML804pin5-gTM66?usp=share_link',
    rating: 2,
    keywords: ['Host Mode', 'Large Screen Ad', 'Sticker', 'Combo'],
  },
  {
    id: '1007',
    category: 'Retail',
    subcategory: 'Supermarket',
    region: 'Japan',
    robotType: 'PuduBot',
    clientName: 'Supermarket',
    videoUrl: 'https://www.youtube.com/watch?v=4ELJ7139yDQ',
    rating: 2,
    keywords: ['Sticker', 'Cruise Mode'],
  },
  {
    id: '1008',
    category: 'Retail',
    subcategory: 'Supermarket',
    region: 'Turkey',
    robotType: 'BellaBot',
    clientName: 'Carrefour',
    videoUrl: 'https://drive.google.com/drive/folders/17b0NptgIjM20Lk0qsLS5TNwGZmzdZy6-?usp=share_link',
    rating: 1,
    keywords: ['Running', 'Sticker'],
  },
  {
    id: '1009',
    category: 'Retail',
    subcategory: 'Supermarket',
    region: 'Jordan',
    robotType: 'BellaBot',
    clientName: 'HEINZ',
    videoUrl: 'https://drive.google.com/file/d/1Nu3H-fPgQqyFXztguSW1i_9u9M_fAvJB/view?usp=share_link',
    rating: 1,
    keywords: ['Sticker', 'Running'],
  },
  {
    id: '1010',
    category: 'Retail',
    subcategory: 'Supermarket',
    region: 'Saudi Arabia',
    robotType: 'KettyBot',
    clientName: 'Carrefour',
    videoUrl: 'https://www.youtube.com/shorts/7fuR0_AgZrA',
    rating: 1,
    keywords: ['Combo: Ketty+Bella'],
  },
  {
    id: '1011',
    category: 'Retail',
    subcategory: 'Supermarket',
    region: 'Russia',
    robotType: 'KettyBot',
    clientName: 'Tabris',
    videoUrl: 'https://drive.google.com/file/d/1uWD3j2bHIAypQ_ZQJcfJWMHtmsuIKMss/view?usp=share_link',
    rating: 1,
    keywords: ['Large Screen Ad', 'Sticker', 'Combo: Ketty+Bella'],
  },
  {
    id: '1012',
    category: 'Retail',
    subcategory: 'Supermarket',
    region: 'South Korea',
    robotType: 'PuduBot',
    clientName: 'Supermarket',
    videoUrl: '',
    rating: 2,
    keywords: ['Sticker', 'Cruise Mode'],
  },

  // --- 3. Retail: Shopping Mall ---
  {
    id: '1101',
    category: 'Retail',
    subcategory: 'Shopping Mall',
    region: 'Saudi Arabia',
    robotType: 'KettyBot',
    clientName: 'Al Othaim Mall',
    videoUrl: 'https://www.youtube.com/watch?v=h6ZaGa8buC4',
    rating: 4,
    keywords: ['Host Mode', 'Large Screen Ad', 'Cruise Mode', 'Recharge'],
  },
  {
    id: '1102',
    category: 'Retail',
    subcategory: 'Shopping Mall',
    region: 'Malaysia',
    robotType: 'KettyBot',
    clientName: 'Sunway Velocity Mall',
    videoUrl: 'https://www.facebook.com/SunwayVelocityMall/videos/723174179226011',
    rating: 3,
    keywords: ['Host Mode', 'Large Screen Ad'],
  },
  {
    id: '1103',
    category: 'Retail',
    subcategory: 'Shopping Mall',
    region: 'Europe',
    robotType: 'KettyBot',
    clientName: 'Mall',
    videoUrl: 'https://www.youtube.com/watch?v=ObeyK-xm2iw',
    rating: 3,
    keywords: ['Large Screen Ad', 'Cruise Mode'],
  },
  {
    id: '1104',
    category: 'Retail',
    subcategory: 'Shopping Mall',
    region: 'Hong Kong',
    robotType: 'KettyBot',
    clientName: 'VELOCITY',
    videoUrl: 'https://www.facebook.com/wen.fun.9/videos/2893321200800194',
    rating: 3,
    keywords: ['Host Mode'],
  },
  {
    id: '1105',
    category: 'Retail',
    subcategory: 'Shopping Mall',
    region: 'Philippines',
    robotType: 'KettyBot',
    clientName: 'AllDay Supermarket',
    videoUrl: 'https://www.facebook.com/PuduRobotics.pk/videos/1328758447971447',
    rating: 2,
    keywords: ['Large Screen Ad', 'Sticker'],
  },
  {
    id: '1106',
    category: 'Retail',
    subcategory: 'Shopping Mall',
    region: 'China',
    robotType: 'PuduBot 2',
    clientName: 'Wanxiang',
    videoUrl: 'https://youtu.be/SN8wnfDJsGI',
    rating: 2,
    keywords: ['Delivery Mode', 'Running', 'Scheduling'],
  },
  {
    id: '1107',
    category: 'Retail',
    subcategory: 'Shopping Mall',
    region: 'Japan',
    robotType: 'PuduBot 2',
    clientName: 'Mall',
    videoUrl: 'https://twitter.com/_incubion/status/1639507527426805760/photo/1',
    rating: 1,
    keywords: ['Large Screen Ad'],
  },
  {
    id: '1108',
    category: 'Retail',
    subcategory: 'Shopping Mall',
    region: 'Australia',
    robotType: 'KettyBot',
    clientName: 'Al Othaim Mall',
    videoUrl: 'https://youtu.be/esBeWUHnz2g',
    rating: 2,
    keywords: ['Sticker'],
  },

  // --- 3. Retail: Others (Electronics, etc) ---
  {
    id: '1201',
    category: 'Retail',
    subcategory: 'Building Material',
    region: 'Netherlands',
    robotType: 'KettyBot',
    clientName: 'Praxis Noordwijk',
    videoUrl: 'https://www.youtube.com/watch?v=kevqdYZFdnw',
    rating: 4,
    keywords: ['Skin', 'Greeter', 'Large Screen Ad', 'Guide'],
  },
  {
    id: '1202',
    category: 'Retail',
    subcategory: 'Electronics',
    region: 'Netherlands',
    robotType: 'KettyBot',
    clientName: 'MediaMarkt',
    videoUrl: 'https://www.youtube.com/watch?v=K34nPERi3Qk',
    rating: 4,
    keywords: ['Large Screen Ad', 'Cruise Mode', 'Guide', 'Skin', 'Greeter'],
  },
  {
    id: '1203',
    category: 'Retail',
    subcategory: 'Electronics',
    region: 'Netherlands',
    robotType: 'BellaBot',
    clientName: 'Media Market',
    videoUrl: 'https://drive.google.com/file/d/1Zx_4M4ZDIXyBQzoRsQyEfJXQ1MPto3ET/view?usp=share_link',
    rating: 1,
    keywords: ['Skin'],
  },
  {
    id: '1204',
    category: 'Retail',
    subcategory: 'Electronics',
    region: 'Austria',
    robotType: 'BellaBot',
    clientName: 'Media Market',
    videoUrl: 'https://drive.google.com/file/d/1-EwvjI-K3fvSO1iOA_ga0gve1xQM_mTF/view?usp=share_link',
    rating: 1,
    keywords: ['Skin', 'Running'],
  },
  {
    id: '1205',
    category: 'Retail',
    subcategory: 'Retail Brand',
    region: 'Jordan',
    robotType: 'BellaBot',
    clientName: 'Coca Cola',
    videoUrl: 'https://drive.google.com/file/d/1kmcd1FmElbcvbvl34cwQyuPOJFTkU1Cg/view?usp=share_link',
    rating: 1,
    keywords: ['Running', 'Touch'],
  },
  {
    id: '1206',
    category: 'Retail',
    subcategory: 'Retail Brand',
    region: 'Jordan',
    robotType: 'BellaBot',
    clientName: 'M&M',
    videoUrl: 'https://drive.google.com/drive/folders/1tRb7_Bmmx5nqngCuz2EToagDfDc7E_wj?usp=share_link',
    rating: 1,
    keywords: ['Skin', 'Running'],
  },
  {
    id: '1207',
    category: 'Retail',
    subcategory: 'Telecom',
    region: 'Australia',
    robotType: 'KettyBot',
    clientName: 'Tienda',
    videoUrl: 'https://drive.google.com/file/d/1oz2eKp6ZQNYlwPIsfmxQq8cvGM1-Jjmd/view?usp=share_link',
    rating: 1,
    keywords: ['Large Screen Ad', 'Running'],
  },

  // --- 4. Other: Medical ---
  {
    id: '1301',
    category: 'Other',
    subcategory: 'Medical',
    region: 'Estonia',
    robotType: 'KettyBot',
    clientName: 'Tartu Ülikooli Kliinikumis',
    videoUrl: 'https://www.youtube.com/shorts/cpmRMVLMw-U',
    rating: 2,
    keywords: ['Greeter', 'Large Screen Ad', 'Recharge'],
  },
  {
    id: '1302',
    category: 'Other',
    subcategory: 'Medical',
    region: 'Hong Kong',
    robotType: 'PuduBot',
    clientName: 'HK Hospitals',
    videoUrl: 'https://youtu.be/eVrR6xqVQUg',
    rating: 3,
    keywords: ['Sticker', 'Cover'],
  },
  {
    id: '1303',
    category: 'Other',
    subcategory: 'Medical',
    region: 'Malaysia',
    robotType: 'BellaBot',
    clientName: 'Sunway Medical Center',
    videoUrl: 'https://drive.google.com/file/d/1moTB5MsbMbEU8HgM5RocPQGG8d7u1BEd/view?usp=share_link',
    rating: 3,
    keywords: ['Delivery Mode', 'Sticker', 'Birthday Mode'],
  },
  {
    id: '1304',
    category: 'Other',
    subcategory: 'Medical',
    region: 'Japan',
    robotType: 'KettyBot',
    clientName: 'Karada Terrace',
    videoUrl: 'https://www.youtube.com/watch?v=5eio-T2mi0I',
    rating: 2,
    keywords: ['Delivery Mode', 'Large Screen Ad'],
  },
  {
    id: '1305',
    category: 'Other',
    subcategory: 'Medical',
    region: 'Australia',
    robotType: 'KettyBot',
    clientName: 'mp orthodontics',
    videoUrl: 'https://drive.google.com/drive/folders/18dEBkLEDTmZyPRTKD3L_9jvOgiKzCiDY?usp=share_link',
    rating: 1,
    keywords: ['Large Screen Ad', 'Running'],
  },
  {
    id: '1306',
    category: 'Other',
    subcategory: 'Medical',
    region: 'Japan',
    robotType: 'KettyBot',
    clientName: 'Hodogaya Eye Clinic',
    videoUrl: 'https://www.youtube.com/watch?v=iYQmjlvTkbg',
    rating: 2,
    keywords: ['Large Screen Ad', 'Delivery Mode', 'Host Mode'],
  },
  {
    id: '1307',
    category: 'Other',
    subcategory: 'Medical',
    region: 'Thailand',
    robotType: 'BellaBot',
    clientName: 'Square Cabin Hospital',
    videoUrl: 'https://www.youtube.com/watch?v=EPkE4JWsTxs',
    rating: 2,
    keywords: ['Running'],
  },
  {
    id: '1308',
    category: 'Other',
    subcategory: 'Medical',
    region: 'South Korea',
    robotType: 'PuduBot',
    clientName: 'Dental Clinic',
    videoUrl: '',
    rating: 3,
    keywords: ['Delivery Mode', 'Cover'],
  },
  {
    id: '1309',
    category: 'Other',
    subcategory: 'Medical',
    region: 'South Korea',
    robotType: 'PuduBot',
    clientName: 'Hospital',
    videoUrl: '',
    rating: 1,
    keywords: ['Cruise Mode'],
  },
  {
    id: '1310',
    category: 'Other',
    subcategory: 'Medical',
    region: 'Thailand',
    robotType: 'PuduBot',
    clientName: 'Hospital Ward',
    videoUrl: '',
    rating: 1,
    keywords: ['Delivery Mode'],
  },

  // --- 4. Other: Office/Factory/Etc ---
  {
    id: '1401',
    category: 'Other',
    subcategory: 'Office',
    region: 'Australia',
    robotType: 'PuduBot',
    clientName: 'Office',
    videoUrl: 'https://youtu.be/6hGBqvXEjwk',
    rating: 1,
    keywords: ['Delivery Mode'],
  },
  {
    id: '1402',
    category: 'Other',
    subcategory: 'Office',
    region: 'Hong Kong',
    robotType: 'KettyBot',
    clientName: 'Innocore',
    videoUrl: 'https://drive.google.com/file/d/1n4B9s1XiqWoYrRFPYVzxy-HjZdgYWGgp/view?usp=share_link',
    rating: 2,
    keywords: ['Spray'],
  },
  {
    id: '1403',
    category: 'Other',
    subcategory: 'Office',
    region: 'China',
    robotType: 'KettyBot',
    clientName: 'Office',
    videoUrl: 'https://youtu.be/hPy6eNk5ToQ',
    rating: 4,
    keywords: ['Running', 'Host Mode', 'Cruise Mode', 'IOT'],
  },
  {
    id: '1404',
    category: 'Other',
    subcategory: 'Event',
    region: 'UAE',
    robotType: 'BellaBot',
    clientName: 'FIRSTGULF',
    videoUrl: 'https://drive.google.com/file/d/1v65XbEZpw1mibfeu72R7EbCPQ9ZZAWy6/view?usp=share_link',
    rating: 1,
    keywords: ['Running'],
  },
  {
    id: '1405',
    category: 'Other',
    subcategory: 'Event',
    region: 'UAE',
    robotType: 'KettyBot',
    clientName: 'FIRSTGULF',
    videoUrl: 'https://drive.google.com/file/d/1NbkH8ZWfm8xcHYLxm2JarvG6YNuqc1yo/view?usp=share_link',
    rating: 1,
    keywords: ['Combo: Ketty+Bella', 'Large Screen Ad'],
  },
  {
    id: '1406',
    category: 'Other',
    subcategory: 'Studio',
    region: 'Italy',
    robotType: 'KettyBot',
    clientName: 'M8 Studio',
    videoUrl: 'https://www.youtube.com/watch?v=0lF12cvbSBo',
    rating: 3,
    keywords: ['Large Screen Ad', 'Host Mode'],
  },
  {
    id: '1407',
    category: 'Other',
    subcategory: 'Event',
    region: 'Malaysia',
    robotType: 'PuduBot 2',
    clientName: 'Association Meeting',
    videoUrl: 'https://youtu.be/D2GVIcjtDBk',
    rating: 2,
    keywords: ['Delivery Mode', 'Scheduling'],
  },
  {
    id: '1408',
    category: 'Other',
    subcategory: 'Event',
    region: 'Saudi Arabia',
    robotType: 'BellaBot',
    clientName: 'MCIT',
    videoUrl: 'https://youtu.be/k6nZpfgIU4Y',
    rating: 2,
    keywords: ['Running'],
  },
  {
    id: '1409',
    category: 'Other',
    subcategory: 'Event',
    region: 'Hong Kong',
    robotType: 'BellaBot',
    clientName: "Maxim's Online Supplier Forum",
    videoUrl: 'https://youtu.be/UXr2ijsdG1E',
    rating: 2,
    keywords: ['Running'],
  },
  {
    id: '1410',
    category: 'Other',
    subcategory: 'Factory',
    region: 'China',
    robotType: 'PuduBot',
    clientName: 'Great Wall Development',
    videoUrl: 'https://youtu.be/cN4i7QDjoKg',
    rating: 3,
    keywords: ['Delivery Mode'],
  },
  {
    id: '1411',
    category: 'Other',
    subcategory: 'Factory',
    region: 'Japan',
    robotType: 'HolaBot',
    clientName: 'Factory',
    videoUrl: 'https://youtu.be/mqTbo54wD14',
    rating: 3,
    keywords: ['Watch', 'Delivery Mode'],
  },
  {
    id: '1412',
    category: 'Other',
    subcategory: 'Factory',
    region: 'Australia',
    robotType: 'PuduBot 2',
    clientName: 'Factory',
    videoUrl: 'https://youtube.com/shorts/rv0FvIEnJqo?feature=share',
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '1413',
    category: 'Other',
    subcategory: 'Factory',
    region: 'Japan',
    robotType: 'HolaBot',
    clientName: 'Seiko Electric',
    videoUrl: 'https://youtu.be/fA-aNYg1sFM',
    rating: 2,
    keywords: ['Delivery Mode'],
  },
  {
    id: '1414',
    category: 'Other',
    subcategory: 'Automotive 4S',
    region: 'Netherlands',
    robotType: 'KettyBot',
    clientName: 'Nissan',
    videoUrl: 'https://www.youtube.com/watch?v=KyVCVUQGwdo',
    rating: 3,
    keywords: ['Host Mode', 'Large Screen Ad'],
  },
  {
    id: '1415',
    category: 'Other',
    subcategory: 'Automotive 4S',
    region: 'Indonesia',
    robotType: 'BellaBot',
    clientName: 'Lexus',
    videoUrl: '', 
    rating: 1,
    keywords: ['Running'],
  },
  {
    id: '1416',
    category: 'Other',
    subcategory: 'Automotive 4S',
    region: 'Thailand',
    robotType: 'KettyBot',
    clientName: 'Honda',
    videoUrl: 'https://drive.google.com/drive/folders/1n4rrrmlH6Uy36NJiavZdjn7BpvTNJW-i?usp=share_link',
    rating: 1,
    keywords: ['Large Screen Ad', 'Running'],
  },
  {
    id: '1417',
    category: 'Other',
    subcategory: 'Nursing Home',
    region: 'Japan',
    robotType: 'BellaBot',
    clientName: 'Smiling Park',
    videoUrl: 'https://drive.google.com/file/d/1AWNVujSOwVtwWih-Zxavl0G7mFliEmSH/view?usp=share_link',
    rating: 4,
    keywords: ['Delivery Mode', 'App Call'],
  },
  {
    id: '1418',
    category: 'Other',
    subcategory: 'Nursing Home',
    region: 'South Korea',
    robotType: 'PuduBot',
    clientName: 'Nursing Home',
    videoUrl: '', 
    rating: 3,
    keywords: ['Sticker', 'Cover'],
  },

  // --- 4. Other: Transport/Entertainment ---
  {
    id: '1501',
    category: 'Other',
    subcategory: 'Exhibition',
    region: 'Ethiopia',
    robotType: 'KettyBot',
    clientName: 'Ethio Telecom',
    videoUrl: 'https://www.youtube.com/watch?v=PeH_FC6EkP4',
    rating: 1,
    keywords: ['Large Screen Ad', 'Running'],
  },
  {
    id: '1502',
    category: 'Other',
    subcategory: 'Transport',
    region: 'Russia',
    robotType: 'KettyBot',
    clientName: 'Train Station',
    videoUrl: 'https://drive.google.com/file/d/1tCPLQ-EDTX5Qj8iE4UbJS5sp57Q9mfy3/view?usp=share_link',
    rating: 2,
    keywords: ['Large Screen Ad', 'Host Mode'],
  },
  {
    id: '1503',
    category: 'Other',
    subcategory: 'Transport',
    region: 'Russia',
    robotType: 'BellaBot',
    clientName: 'Sheremetyevo Airport',
    videoUrl: 'https://drive.google.com/file/d/1z34Uy2Ec2j5A__iNpTUq2iG6_T-EZI-W/view?usp=share_link',
    rating: 1,
    keywords: ['Running'],
  },
  {
    id: '1504',
    category: 'Other',
    subcategory: 'Media',
    region: 'Europe',
    robotType: 'BellaBot',
    clientName: 'CGTN',
    videoUrl: 'https://drive.google.com/file/d/1U2UJWoNo18w9Rjl1B1otCyB2u7tOi6rF/view?usp=share_link',
    rating: 2,
    keywords: ['Touch', 'Delivery Mode'],
  },
  {
    id: '1505',
    category: 'Other',
    subcategory: 'TV Show',
    region: 'Netherlands',
    robotType: 'BellaBot',
    clientName: 'WIE KENT NEDERLAND SHOW',
    videoUrl: 'https://youtu.be/bY6bEO363Vg',
    rating: 2,
    keywords: ['Running'],
  },
  {
    id: '1506',
    category: 'Other',
    subcategory: 'Library',
    region: 'Canada',
    robotType: 'KettyBot',
    clientName: 'St.Catharines library',
    videoUrl: 'https://www.youtube.com/watch?v=JdD9PxIoDx8',
    rating: 1,
    keywords: ['Large Screen Ad', 'Running'],
  },
  {
    id: '1507',
    category: 'Other',
    subcategory: 'Entertainment',
    region: 'China',
    robotType: 'PuduBot 2',
    clientName: 'KTV',
    videoUrl: 'https://youtu.be/1H65BMz9XuA',
    rating: 2,
    keywords: ['Delivery Mode', 'Birthday Mode'],
  },
  {
    id: '1508',
    category: 'Other',
    subcategory: 'Entertainment',
    region: 'Australia',
    robotType: 'PuduBot 2',
    clientName: 'Racing Center',
    videoUrl: 'https://www.facebook.com/photo/?fbid=180091501437042&set=pcb.180091554770370',
    rating: 2,
    keywords: ['Running'],
  },
  {
    id: '1509',
    category: 'Other',
    subcategory: 'Retail',
    region: 'France',
    robotType: 'KettyBot',
    clientName: 'Joueclub',
    videoUrl: '', 
    rating: 2,
    keywords: ['Running'],
  },
  {
    id: '1510',
    category: 'Other',
    subcategory: 'Entertainment',
    region: 'Russia',
    robotType: 'KettyBot',
    clientName: 'Monster Hills',
    videoUrl: 'https://www.youtube.com/watch?v=aC9KFjCZ_oA',
    rating: 1,
    keywords: ['Large Screen Ad', 'Running'],
  },
  {
    id: '1511',
    category: 'Other',
    subcategory: 'Entertainment',
    region: 'Canada',
    robotType: 'KettyBot',
    clientName: 'Xtreme Trampoline Park',
    videoUrl: 'https://youtu.be/KgPh6YxtmTk',
    rating: 4,
    keywords: ['Combo: Bella+Puductor+CC1'],
  },
  {
    id: '1512',
    category: 'Other',
    subcategory: 'Entertainment',
    region: 'Poland',
    robotType: 'BellaBot',
    clientName: 'Hula Park',
    videoUrl: 'https://drive.google.com/file/d/11ZzGCT3K6mLFbhLQ1Vpy7FRn4uN6LzZ9/view?usp=share_link',
    rating: 2,
    keywords: ['Sticker', 'Running'],
  },

  // --- 5. Cleaning ---
  {
    id: '1601',
    category: 'Cleaning',
    subcategory: 'SH1',
    region: 'Global',
    robotType: 'SH1',
    clientName: 'Functional Demo - Oil Cleaning',
    videoUrl: 'https://drive.google.com/file/d/1aJW6LhU8AOaLyeoX-hXpyArhA3Y489_L/view?usp=share_link',
    rating: 5,
    keywords: ['Oil Cleaning'],
  },
  {
    id: '1602',
    category: 'Cleaning',
    subcategory: 'SH1',
    region: 'Global',
    robotType: 'SH1',
    clientName: 'Functional Demo - Washing',
    videoUrl: 'https://drive.google.com/file/d/1eBrjkTRlxsmNaUJZaGGFPUzW2SySygZf/view?usp=share_link',
    rating: 5,
    keywords: ['Washing'],
  },
  {
    id: '1603',
    category: 'Cleaning',
    subcategory: 'SH1',
    region: 'Global',
    robotType: 'SH1',
    clientName: 'Functional Demo - Slope',
    videoUrl: 'https://drive.google.com/file/d/1gkpLjev9MNRQnjXya8ICTt4U7DPyGO5r/view?usp=share_link',
    rating: 5,
    keywords: ['Slope Cleaning'],
  },
  {
    id: '1604',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'Canada',
    robotType: 'CC1',
    clientName: 'Restaurant',
    videoUrl: '', 
    rating: 4,
    keywords: ['Cement Tile'],
  },
  {
    id: '1605',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'Russia',
    robotType: 'CC1',
    clientName: 'Supermarket',
    videoUrl: '', 
    rating: 4,
    keywords: ['Water Cleaning'],
  },
  {
    id: '1606',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'Russia',
    robotType: 'CC1',
    clientName: 'Parking Lot',
    videoUrl: '', 
    rating: 4,
    keywords: ['Cement Floor'],
  },
  {
    id: '1607',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'China',
    robotType: 'CC1',
    clientName: 'Train Station',
    videoUrl: '', 
    rating: 4,
    keywords: ['Marble'],
  },
  {
    id: '1608',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'Singapore',
    robotType: 'CC1',
    clientName: 'Airport',
    videoUrl: '', 
    rating: 4,
    keywords: ['Carpet'],
  },
  {
    id: '1609',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'Global',
    robotType: 'CC1',
    clientName: 'Retail',
    videoUrl: '', 
    rating: 4,
    keywords: ['Marble'],
  },
  {
    id: '1610',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'Russia',
    robotType: 'CC1',
    clientName: 'Gym',
    videoUrl: '', 
    rating: 4,
    keywords: ['Wood Floor'],
  },
  {
    id: '1611',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'Japan',
    robotType: 'CC1',
    clientName: 'Office',
    videoUrl: '', 
    rating: 4,
    keywords: ['Short Carpet'],
  },
  {
    id: '1612',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'China',
    robotType: 'CC1',
    clientName: 'Office',
    videoUrl: '', 
    rating: 4,
    keywords: ['Hard Floor', 'Stain'],
  },
  {
    id: '1613',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'Russia',
    robotType: 'CC1',
    clientName: 'Bank',
    videoUrl: '', 
    rating: 4,
    keywords: ['Hard Floor'],
  },
  {
    id: '1614',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'Japan',
    robotType: 'CC1',
    clientName: 'Hospital',
    videoUrl: '', 
    rating: 4,
    keywords: ['Hard Floor', 'Corridor'],
  },
  {
    id: '1615',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'Russia',
    robotType: 'CC1',
    clientName: 'Showroom',
    videoUrl: '', 
    rating: 4,
    keywords: ['Short Carpet'],
  },
  {
    id: '1616',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'Costa Rica',
    robotType: 'CC1',
    clientName: 'Office',
    videoUrl: 'https://drive.google.com/drive/folders/1m1nlp0JIk5rRg1kn36QT2k_5cS0EIby-?usp=share_link',
    rating: 4,
    keywords: ['Wood Floor', 'Tile'],
  },
  {
    id: '1617',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'China',
    robotType: 'CC1',
    clientName: 'Subway Station',
    videoUrl: 'https://drive.google.com/file/d/1ohkEl2LV9tnySCr3hD0y9Wlkylgu_xWf/view?usp=share_link',
    rating: 4,
    keywords: ['Marble'],
  },
  {
    id: '1618',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'China',
    robotType: 'CC1',
    clientName: 'School',
    videoUrl: 'https://youtu.be/FtAGFgwR7Rw',
    rating: 4,
    keywords: ['Hard Floor'],
  },
  {
    id: '1619',
    category: 'Cleaning',
    subcategory: 'CC1',
    region: 'Canada',
    robotType: 'CC1',
    clientName: 'Amusement Park',
    videoUrl: 'https://youtu.be/KgPh6YxtmTk',
    rating: 4,
    keywords: ['Interview', 'Combo'],
  },
];
